In [1]:
import pandas as pd
import numpy as np
from IPython.display import display
pd.options.display.max_columns = None
pd.options.display.max_rows = None
from functools import reduce
# Reading different states gdp data
AndhraPradesh1   = pd.read_csv('data/gdp/gdp_AndhraPradesh1.csv' , encoding = 'utf-8')
AndhraPradesh2   = pd.read_csv('data/gdp/gdp_AndhraPradesh2.csv' , encoding = 'utf-8')
ArunachalPradesh1= pd.read_csv('data/gdp/gdp_ArunachalPradesh.csv' , encoding = 'utf-8')
Assam1           = pd.read_csv('data/gdp/gdp_Assam1.csv' , encoding = 'utf-8')
Assam2           = pd.read_csv('data/gdp/gdp_Assam2.csv' , encoding = 'utf-8')
Bihar1           = pd.read_csv('data/gdp/gdp_Bihar1.csv' , encoding = 'utf-8')
Bihar2           = pd.read_csv('data/gdp/gdp_Bihar2.csv' , encoding = 'utf-8')
Chattisgarh1     = pd.read_csv('data/gdp/gdp_Chattisgarh.csv' , encoding = 'utf-8')
Haryana1         = pd.read_csv('data/gdp/gdp_Haryana.csv' , encoding = 'utf-8')
HimachalPradesh1 = pd.read_csv('data/gdp/gdp_HimachalPradesh.csv' , encoding = 'utf-8')
Jharkhand1       = pd.read_csv('data/gdp/gdp_Jharkhand.csv' , encoding = 'utf-8')
Karnataka1       = pd.read_csv('data/gdp/gdp_Karnataka1.csv' , encoding = 'utf-8')
Karnataka2       = pd.read_csv('data/gdp/gdp_Karnataka2.csv' , encoding = 'utf-8')
Kerala1          = pd.read_csv('data/gdp/gdp_Kerala1.csv' , encoding = 'utf-8')
Kerala2          = pd.read_csv('data/gdp/gdp_Kerala2.csv' , encoding = 'utf-8')
MadhyaPradesh1   = pd.read_csv('data/gdp/gdp_MadhyaPradesh.csv' , encoding = 'utf-8')
Maharashtra1     = pd.read_csv('data/gdp/gdp_Maharashtra1.csv' , encoding = 'utf-8')
Maharashtra2     = pd.read_csv('data/gdp/gdp_Maharashtra2.csv' , encoding = 'utf-8')
Manipur1         = pd.read_csv('data/gdp/gdp_Manipur.csv' , encoding = 'utf-8')
Meghalaya1       = pd.read_csv('data/gdp/gdp_Meghalaya.csv' , encoding = 'utf-8')
Mizoram1         = pd.read_csv('data/gdp/gdp_Mizoram.csv' , encoding = 'utf-8')
Odisha1          = pd.read_csv('data/gdp/gdp_Odisha1.csv' , encoding = 'utf-8')
Odisha2          = pd.read_csv('data/gdp/gdp_Odisha2.csv' , encoding = 'utf-8')
Punjab1          = pd.read_csv('data/gdp/gdp_Punjab1.csv' , encoding = 'utf-8')
Punjab2          = pd.read_csv('data/gdp/gdp_Punjab2.csv' , encoding = 'utf-8')
Rajasthan1       = pd.read_csv('data/gdp/gdp_Rajasthan1.csv' , encoding = 'utf-8')
Rajasthan2       = pd.read_csv('data/gdp/gdp_Rajasthan2.csv' , encoding = 'utf-8')
Sikkim1          = pd.read_csv('data/gdp/gdp_Sikkim.csv' , encoding = 'utf-8')
Tamilnadu1       = pd.read_csv('data/gdp/gdp_Tamilnadu.csv' , encoding = 'utf-8')
Uttarakhand1     = pd.read_csv('data/gdp/gdp_Uttarakhand.csv' , encoding = 'utf-8')
UttarPradesh1    = pd.read_csv('data/gdp/gdp_UttarPradesh1.csv' , encoding = 'utf-8')
UttarPradesh2    = pd.read_csv('data/gdp/gdp_UttarPradesh2.csv' , encoding = 'utf-8')
WestBengal1      = pd.read_csv('data/gdp/gdp_WestBengal1.csv' , encoding = 'utf-8')
WestBengal2      = pd.read_csv('data/gdp/gdp_WestBengal2.csv' , encoding = 'utf-8')

# Read elementary school data
eleschl = pd.read_csv('data/elementary_2015_16.csv', encoding='UTF-8')
census = pd.read_csv('data/census-2011.csv' , encoding='UTF-8')
# Read crime data
dataMissChildren = pd.read_csv('data/crimes/missing_traced_children.csv')
dataCrime        = pd.read_csv('data/crimes/crimes.csv')
dataCyberCrm     = pd.read_csv('data/crimes/cyber_crime.csv')
dataChldCrm      = pd.read_csv('data/crimes/crime_against_children.csv')
dataTrafficing   = pd.read_csv('data/crimes/trafficing.csv')
dataRapeVictm    = pd.read_csv('data/crimes/rape_victims.csv')
dataKidnapping   = pd.read_csv('data/crimes/kidnapping.csv')
dataJuvenileCrm  = pd.read_csv('data/crimes/juvenile_crime.csv')
dataMurderVictm  = pd.read_csv('data/crimes/murder_victims.csv')
dataCorruption   = pd.read_csv('data/crimes/coruption_case.csv')
dataCurSeized    = pd.read_csv('data/crimes/currency_siezed.csv')
dataJuvArrest    = pd.read_csv('data/crimes/juvenile_arrested_bckgrnd.csv')
dataMrdrMotive   = pd.read_csv('data/crimes/murder_motives.csv')
dataVioCrm       = pd.read_csv('data/crimes/violent_crime_incidence.csv')

# Manipulating GDP data

In [2]:
# Function to append two gdp csv file
def appendGdp(state1,state2):
    state1 =  state1.rename(columns=lambda x: x.strip())
    state2 =  state2.rename(columns=lambda x: x.strip())
    state  =  state1.append(state2,sort=False)[state1.columns.tolist()].reset_index()
    state  =  state.drop(columns=['index'], axis = 0)
    return state;

# Function to change column header of gdp dataframe
def changeGdp(stateName):
    stateName         = stateName.rename(columns=lambda x: x.strip())
    stateName         = stateName.transpose().reset_index()
    stateName.columns = stateName.iloc[1] + '|' + stateName.iloc[0]
    stateName         = stateName.rename(columns={'Description|Year':'DISTRICT NAME'})
    stateName         = stateName.drop([0, 1])
    return stateName;

# Manupulating different states gdp data
AndhraPradesh = appendGdp(AndhraPradesh1 ,AndhraPradesh2)
AndhraPradesh = AndhraPradesh.drop([5,6,7,8,14,15,16])
AndhraPradesh = changeGdp(AndhraPradesh)
AndhraPradesh['STATE NAME'] = 'ANDHRA PRADESH'

ArunachalPradesh = changeGdp(ArunachalPradesh1)
ArunachalPradesh['STATE NAME'] = 'ARUNACHAL PRADESH'

Assam         = appendGdp(Assam1,Assam2)
Assam         = changeGdp(Assam)
Assam['STATE NAME'] = 'ASSAM'

Bihar         = appendGdp(Bihar1,Bihar2)
Bihar         = Bihar.drop([5])
Bihar         = changeGdp(Bihar)
Bihar['STATE NAME'] = 'BIHAR'

Chattisgarh = changeGdp(Chattisgarh1)
Chattisgarh['STATE NAME'] = 'CHATTISGARH'

Haryana     =  changeGdp(Haryana1)
Haryana['STATE NAME'] = 'HARYANA'

HimachalPradesh = changeGdp(HimachalPradesh1)
HimachalPradesh['STATE NAME'] = 'HIMACHAL PRADESH'

Jharkhand    = changeGdp(Jharkhand1)
Jharkhand['STATE NAME'] = 'JHARKHAND'

Karnataka   = appendGdp(Karnataka1,Karnataka2)
Karnataka   = changeGdp(Karnataka)
Karnataka['STATE NAME'] = 'KARNATAKA'

Kerala      =  appendGdp(Kerala1,Kerala2)
Kerala      = Kerala.drop([6,7,14])
Kerala      = changeGdp(Kerala)
Kerala['STATE NAME'] = 'KERALA'

MadhyaPradesh = changeGdp(MadhyaPradesh1)
MadhyaPradesh['STATE NAME'] = 'MADHYA PRADESH'

Maharashtra  = appendGdp(Maharashtra1,Maharashtra2)
Maharashtra  = Maharashtra.drop([6,7,14])
Maharashtra  = changeGdp(Maharashtra)
Maharashtra['STATE NAME'] = 'MAHARASHTRA'

Manipur      = changeGdp(Manipur1)
Manipur['STATE NAME'] = 'MANIPUR'

Meghalaya    = changeGdp(Meghalaya1)
Meghalaya['STATE NAME'] = 'MEGHALAYA'

Mizoram     = changeGdp(Mizoram1)
Mizoram['STATE NAME'] = 'MIZORAM'

Odisha      = appendGdp(Odisha1,Odisha2)
Odisha      = Odisha.drop([5,6,7,13,14])
Odisha      = changeGdp(Odisha)
Odisha['STATE NAME'] = 'ODISHA'

Punjab      = appendGdp(Punjab1,Punjab2)
Punjab      = Punjab.drop([5,6,12])
Punjab      = changeGdp(Punjab)
Punjab['STATE NAME'] = 'PUNJAB'

Rajasthan   = appendGdp(Rajasthan1,Rajasthan2)
Rajasthan   = Rajasthan.drop([5,6,12])
Rajasthan   = changeGdp(Rajasthan)
Rajasthan['STATE NAME'] = 'RAJASTHAN'

Sikkim      = changeGdp(Sikkim1)
Sikkim['STATE NAME'] = 'SIKKIM'

Tamilnadu   = changeGdp(Tamilnadu1)
Tamilnadu['STATE NAME'] = 'TAMIL NADU'

Uttarakhand = changeGdp(Uttarakhand1)
Uttarakhand['STATE NAME'] = 'UTTARAKHAND'

UttarPradesh = appendGdp(UttarPradesh1,UttarPradesh2)
UttarPradesh = UttarPradesh.drop([5,6,12])
UttarPradesh = changeGdp(UttarPradesh)
UttarPradesh['STATE NAME'] = 'UTTAR PRADESH'

WestBengal  = appendGdp(WestBengal1,WestBengal2)
WestBengal  = WestBengal.drop([5,6,7,13,14])
WestBengal  = changeGdp(WestBengal)
WestBengal['STATE NAME'] = 'WEST BENGAL'

# Appending all the states into single dataframe
dataGDP = AndhraPradesh.append([ArunachalPradesh,Assam,Bihar,Chattisgarh,Haryana,HimachalPradesh,Jharkhand,Karnataka,
          Kerala,MadhyaPradesh,Maharashtra,Manipur,Meghalaya,Mizoram,Odisha,Punjab,Rajasthan,Sikkim,Tamilnadu,Uttarakhand,
          UttarPradesh,WestBengal],sort=False)
dataGDP['DISTRICT NAME'] = dataGDP['DISTRICT NAME'].str.title()

# GDP data from 1999-2013

In [3]:
dataGDP.head()

,DISTRICT NAME,GDP (in Rs. Cr.)|1999-00,GDP (in Rs. Cr.)|2000-01,GDP (in Rs. Cr.)|2001-02,GDP (in Rs. Cr.)|2002-03,GDP (in Rs. Cr.)|2003-04,Growth Rate % (YoY)|2000-01,Growth Rate % (YoY)|2001-02,Growth Rate % (YoY)|2002-03,Growth Rate % (YoY)|2003-04,Growth Rate % (YoY)|2004-05,GDP (in Rs. Cr.)|2004-05,GDP (in Rs. Cr.)|2005-06,GDP (in Rs. Cr.)|2006-07,GDP (in Rs. Cr.)|2007-08,GDP (in Rs. Cr.)|2008-09,GDP (in Rs. Cr.)|2009-10,GDP (in Rs. Cr.)|2010-11,GDP (in Rs. Cr.)|2011-12,GDP (in Rs. Cr.)|2012-13,Growth Rate % (YoY)|2005-06,Growth Rate % (YoY)|2006-07,Growth Rate % (YoY)|2007-08,Growth Rate % (YoY)|2008-09,Growth Rate % (YoY)|2009-10,Growth Rate % (YoY)|2010-11,Growth Rate % (YoY)|2011-12,Growth Rate % (YoY)|2012-13,STATE NAME
2,Adilabad,3463.28,3742.69,4209.4,4099.29,4781.85,8.06779,12.4699,-2.61581,16.6507,-4.99911,6527.41,6813.28,7650.79,8316.5,9342.33,9514,9962,10567,11111,4.37953,12.2923,8.70119,12.3349,1.83755,4.70885,6.07308,5.1481,ANDHRA PRADESH
3,Anantapur,4728.59,6497.7,5726.9,5728.86,6083.64,37.4131,-11.8627,0.0342244,6.19286,29.5042,9286.21,9603.8,10080.9,12799.6,12759.9,13532,14793,15799,16563,3.42002,4.96751,26.969,-0.309776,6.05074,9.31865,6.80051,4.83575,ANDHRA PRADESH
4,Chittoor,5395.57,6223.34,6679.35,6490.28,7100.34,15.3417,7.32742,-2.83066,9.39959,10.3075,9048.39,10086.2,10656.3,12095.4,12528.1,12875,14685,15423,16144,11.4691,5.6527,13.5042,3.57815,2.76865,14.0583,5.02554,4.67484,ANDHRA PRADESH
5,Godavari East,9507.67,9664.92,10293.7,10774.7,11955.3,1.65393,6.50621,4.67216,10.9576,6.11727,17289.9,16223.8,18446.6,20421.4,21859.9,22527,21840,22984,24317,-6.16603,13.701,10.7056,7.04387,3.05171,-3.04967,5.2381,5.79969,ANDHRA PRADESH
6,Godavari West,7398,7679.4,7581.59,8157.23,9285.8,3.80373,-1.27367,7.5926,13.8352,8.9779,12704.4,12404.2,13069,15287.7,14501.2,15771,18355,18931,20248,-2.36288,5.3593,16.9764,-5.14415,8.75622,16.3845,3.13811,6.95684,ANDHRA PRADESH

# Census district data 2011

In [4]:
census.head()

,District code,STATE NAME,DISTRICT NAME,Population,Male,Female,Literate,Male_Literate,Female_Literate,SC,Male_SC,Female_SC,ST,Male_ST,Female_ST,Workers,Male_Workers,Female_Workers,Main_Workers,Marginal_Workers,Non_Workers,Cultivator_Workers,Agricultural_Workers,Household_Workers,Other_Workers,Hindus,Muslims,Christians,Sikhs,Buddhists,Jains,Others_Religions,Religion_Not_Stated,LPG_or_PNG_Households,Housholds_with_Electric_Lighting,Households_with_Internet,Households_with_Computer,Rural_Households,Urban_Households,Households,Below_Primary_Education,Primary_Education,Middle_Education,Secondary_Education,Higher_Education,Graduate_Education,Other_Education,Literate_Education,Illiterate_Education,Total_Education,Age_Group_0_29,Age_Group_30_49,Age_Group_50,Age not stated,Households_with_Bicycle,Households_with_Car_Jeep_Van,Households_with_Radio_Transistor,Households_with_Scooter_Motorcycle_Moped,Households_with_Telephone_Mobile_Phone_Landline_only,Households_with_Telephone_Mobile_Phone_Mobile_only,Households_with_TV_Computer_Laptop_Telephone_mobile_phone_and_Scooter_Car,Households_with_Television,Households_with_Telephone_Mobile_Phone,Households_with_Telephone_Mobile_Phone_Both,Condition_of_occupied_census_houses_Dilapidated_Households,Households_with_separate_kitchen_Cooking_inside_house,Having_bathing_facility_Total_Households,Having_latrine_facility_within_the_premises_Total_Households,Ownership_Owned_Households,Ownership_Rented_Households,Type_of_bathing_facility_Enclosure_without_roof_Households,Type_of_fuel_used_for_cooking_Any_other_Households,Type_of_latrine_facility_Pit_latrine_Households,Type_of_latrine_facility_Other_latrine_Households,Type_of_latrine_facility_Night_soil_disposed_into_open_drain_Households,Type_of_latrine_facility_Flush_pour_flush_latrine_connected_to_other_system_Households,Not_having_bathing_facility_within_the_premises_Total_Households,Not_having_latrine_facility_within_the_premises_Alternative_source_Open_Households,Main_source_of_drinking_water_Un_covered_well_Households,Main_source_of_drinking_water_Handpump_Tubewell_Borewell_Households,Main_source_of_drinking_water_Spring_Households,Main_source_of_drinking_water_River_Canal_Households,Main_source_of_drinking_water_Other_sources_Households,Main_source_of_drinking_water_Other_sources_Spring_River_Canal_Tank_Pond_Lake_Other_sources__Households,Location_of_drinking_water_source_Near_the_premises_Households,Location_of_drinking_water_source_Within_the_premises_Households,Main_source_of_drinking_water_Tank_Pond_Lake_Households,Main_source_of_drinking_water_Tapwater_Households,Main_source_of_drinking_water_Tubewell_Borehole_Households,Household_size_1_person_Households,Household_size_2_persons_Households,Household_size_1_to_2_persons,Household_size_3_persons_Households,Household_size_3_to_5_persons_Households,Household_size_4_persons_Households,Household_size_5_persons_Households,Household_size_6_8_persons_Households,Household_size_9_persons_and_above_Households,Location_of_drinking_water_source_Away_Households,Married_couples_1_Households,Married_couples_2_Households,Married_couples_3_Households,Married_couples_3_or_more_Households,Married_couples_4_Households,Married_couples_5__Households,Married_couples_None_Households,Power_Parity_Less_than_Rs_45000,Power_Parity_Rs_45000_90000,Power_Parity_Rs_90000_150000,Power_Parity_Rs_45000_150000,Power_Parity_Rs_150000_240000,Power_Parity_Rs_240000_330000,Power_Parity_Rs_150000_330000,Power_Parity_Rs_330000_425000,Power_Parity_Rs_425000_545000,Power_Parity_Rs_330000_545000,Power_Parity_Above_Rs_545000,Total_Power_Parity
0,1,JAMMU & KASHMIR,Kupwara,870354,474190,396164,439654,282823,156831,1048,1046,2,70352,36913,33439,229064,190899,38165,123837,105227,641290,34680,56759,7946,129679,37128,823286,1700,5600,66,39,13,2522,15828,83071,762,5256,158438,23226,181664,60616,101642,99947,74948,39709,21751,6402,405015,289765,694780,600759,178435,89679,1481,3019,2988,59480,1808,1445,53437,495,26828,56495,1613,8463,104172,66361,54335,104807,618,3667,167,9791,21902,2269,10919,40416,44123,11127,5030,1902,24776,6597,34882,37849,22747,1607,50339,2066,911,4036,4947,6396,31982,10700,14886,42727,27121,46181,80569,14618,2218,2622,330,74,8968,259,494,94,588,71,101,172,74,10,84,15,1119
1,2,JAMMU & KASHMIR,Badgam,753745,398041,355704,335649,207741,127908,368,343,25,23912,12383,11529,214866,162578,52288,132003,82863,538879,55299,36630,29102,93835,10110,736054,1489,5559,47,6,2,478,15118,90190,1999,5892,160649,27190,187839,68336,80862,83141,66459,41367,27950,6857,374972,342646,717618,503223,160933,88978,611,10013,5091,66814,5848,2509,65783,1655,54170,72197,3905,3733,88806,83385,83615,98036,609,3959,971,7013,43953,1779,9208,15834,10642,699,9864,453,13064,1052,14705,33558,51358,136,73303,2321,845,2173,3018,3743,23640,7998,11899,59121,13440,14303,71441,15255,2962,3493,452,79,9030,201,436,126,562,72,89,161,96,28,124,18,1066
2,3,JAMMU & KASHMIR,Leh(Ladakh),133487,78971,54516,93770,62834,30936,488,444,44,95857,47543,48314,75079,53265,21814,57125,17954,58408,20869,1645,1020,51545,22882,19057,658,1092,88635,103,54,1006,13645,17250,574,2150,36920,17474,54394,10452,15181,17900,16265,8923,6197,575,75493,32637,108130,70703,41515,21019,250,609,4271,15210,1289,2646,6331,971,13597,13836,4859,371,20134,10304,18780,19387,893,920,1,14980,2117,53,695,10473,1781,64,5991,620,6115,1565,8355,10962,3031,55,6254,135,1630,1483,3113,2302,10528,4422,3804,5378,1758,6784,12742,3492,716,835,87,32,3708,33,76,46,122,15,22,37,20,14,34,17,242
3,4,JAMMU & KASHMIR,Kargil,140802,77785,63017,86236,56301,29935,18,12,6,122336,62652,59684,51873,39839,12034,28941,22932,88929,8266,3763,1222,38622,10341,108239,604,1171,20126,28,4,289,3285,15824,235,1005,40370,7774,48144,12732,19083,20874,16938,9826,3077,408,82938,39854,122792,87532,35561,17488,221,488,1847,10895,652,899,7733,249,8008,10562,1930,575,17751,11887,17649,16646,1419,330,376,1704,4732,37,9610,6325,482,1,3289,323,2641,907,4068,9218,1963,197,10769,19,689,834,1523,983,4991,1652,2356,6832,4866,7031,10366,3835,1252,1643,308,83,2368,39,87,27,114,12,18,30,19,3,22,7,214
4,5,JAMMU & KASHMIR,Punch,476835,251899,224936,261724,163333,98391,556,406,150,176101,90274,85827,161393,117677,43716,73247,88146,315442,54264,31583,3930,71616,32604,431279,958,11188,83,10,2,711,13160,62900,346,3342,132139,15269,147408,55762,72024,69219,46062,29517,13962,1884,288430,164044,452474,304979,109818,61334,704,846,1731,37412,2407,1908,31773,276,16022,36358,2677,2047,78572,19789,16586,87711,762,3421,28,532,971,338,1174,69089,70470,17702,4036,12448,1351,5351,19458,33146,17078,308,43697,234,1531,7435,8966,10664,44517,15825,18028,31443,3952,38654,70995,9180,1148,1250,87,15,7453,117,268,78,346,35,50,85,59,8,67,12,629

# Elementary school data 2015-16

In [5]:
eleschl['DISTRICT NAME'] = eleschl['DISTRICT NAME'].str.title()
eleschl.head()

,Unnamed: 0,YEAR,STATE NAME,DISTRICT NAME,TOTAL POULATION,PERCENTAGE URBAN POPULATION,0-6 POPULATION,GROWTH RATE,SEX RATIO,PERCENTAGE SC POPULATION,PERCENTAGE ST POPULATION,OVERALL LITERACY,FEMALE LITERACY,MALE LITERACY,AREA (SQ. KM) (AREA SQKM),AGE GROUP 6 TO 10 (TOT 6 10 15),AGE GROUP 11 TO 13 (TOT 11 13 15),PRIMARY ONLY (SCH1),PRIMARY WITH UPPER PRIMARY (SCH2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SCH3),UPPER PRIMARY ONLY (SCH4),UPPER PRIMARY WITH SEC./H.SEC (SCH5),PRIMARY WITH UPPER PRIMARY SEC (SCH6),UPPER PRIMARY WITH SEC. (SCH7),NO RESPONSE (SCH9),TOTAL (SCHTOT),PRIMARY ONLY (SCH1G),PRIMARY WITH UPPER PRIMARY (SCH2G),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SCH3G),UPPER PRIMARY ONLY (SCH4G),UPPER PRIMARY WITH SEC./H.SEC (SCH5G),PRIMARY WITH UPPER PRIMARY SEC (SCH6G),UPPER PRIMARY WITH SEC. (SCH7G),NO RESPONSE (SCH9G),TOTAL (SCHTOTG),PRIMARY ONLY (SCH1P),PRIMARY WITH UPPER PRIMARY (SCH2P),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SCH3P),UPPER PRIMARY ONLY (SCH4P),UPPER PRIMARY WITH SEC./H.SEC (SCH5P),PRIMARY WITH UPPER PRIMARY SEC (SCH6P),UPPER PRIMARY WITH SEC. (SCH7P),NO RESPONSE (SCH9P),TOTAL (SCHTOTP),PRIMARY ONLY (SCH1M),PRIMARY WITH UPPER PRIMARY (SCH2M),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SCH3M),UPPER PRIMARY ONLY (SCH4M),UPPER PRIMARY WITH SEC./H.SEC (SCH5M),PRIMARY WITH UPPER PRIMARY SEC (SCH6M),UPPER PRIMARY WITH SEC. (SCH7M),NO RESPONSE (SCH9M),TOTAL (SCHTOTM),PRIMARY ONLY (SCH1GR),PRIMARY WITH UPPER PRIMARY (SCH2GR),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SCH3GR),UPPER PRIMARY ONLY (SCH4GR),UPPER PRIMARY WITH SEC./H.SEC (SCH5GR),PRIMARY WITH UPPER PRIMARY SEC (SCH6GR),UPPER PRIMARY WITH SEC. (SCH7GR),NO RESPONSE (SCH9GR),TOTAL (SCHTOTGR),PRIMARY ONLY (SCH1GA),PRIMARY WITH UPPER PRIMARY (SCH2GA),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SCH3GA),UPPER PRIMARY ONLY (SCH4GA),UPPER PRIMARY WITH SEC./H.SEC (SCH5GA),PRIMARY WITH UPPER PRIMARY SEC (SCH6GA),UPPER PRIMARY WITH SEC. (SCH7GA),NO RESPONSE (SCH9GA),TOTAL (SCHTOTGA),PRIMARY ONLY (SCH1PR),PRIMARY WITH UPPER PRIMARY (SCH2PR),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SCH3PR),UPPER PRIMARY ONLY (SCH4PR),UPPER PRIMARY WITH SEC./H.SEC (SCH5PR),PRIMARY WITH UPPER PRIMARY SEC (SCH6PR),UPPER PRIMARY WITH SEC. (SCH7PR),NO RESPONSE (SCH9PR),TOTAL (SCHTOTPR),PRIMARY ONLY (SCHBOY1),PRIMARY WITH UPPER PRIMARY (SCHBOY2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SCHBOY3),UPPER PRIMARY ONLY (SCHBOY4),UPPER PRIMARY WITH SEC./H.SEC (SCHBOY5),PRIMARY WITH UPPER PRIMARY SEC (SCHBOY6),UPPER PRIMARY WITH SEC. (SCHBOY7),NO RESPONSE (SCHBOY9),TOTAL (SCHBOYTOT),PRIMARY ONLY (SCHGIR1),PRIMARY WITH UPPER PRIMARY (SCHGIR2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SCHGIR3),UPPER PRIMARY ONLY (SCHGIR4),UPPER PRIMARY WITH SEC./H.SEC (SCHGIR5),PRIMARY WITH UPPER PRIMARY SEC (SCHGIR6),UPPER PRIMARY WITH SEC. (SCHGIR7),NO RESPONSE (SCHGIR9),TOTAL (SCHGIRTOT),PRIMARY ONLY (ENR1),PRIMARY WITH UPPER PRIMARY (ENR2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (ENR3),UPPER PRIMARY ONLY (ENR4),UPPER PRIMARY WITH SEC./H.SEC (ENR5),PRIMARY WITH UPPER PRIMARY SEC (ENR6),UPPER PRIMARY WITH SEC. (ENR7),NO RESPONSE (ENR9),TOTAL (ENRTOT),PRIMARY ONLY (ENR1G),PRIMARY WITH UPPER PRIMARY (ENR2G),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (ENR3G),UPPER PRIMARY ONLY (ENR4G),UPPER PRIMARY WITH SEC./H.SEC (ENR5G),PRIMARY WITH UPPER PRIMARY SEC (ENR6G),UPPER PRIMARY WITH SEC. (ENR7G),NO RESPONSE (ENR9G),TOTAL (ENRTOTG),PRIMARY ONLY (ENR1P),PRIMARY WITH UPPER PRIMARY (ENR2P),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (ENR3P),UPPER PRIMARY ONLY (ENR4P),UPPER PRIMARY WITH SEC./H.SEC (ENR5P),PRIMARY WITH UPPER PRIMARY SEC (ENR6P),UPPER PRIMARY WITH SEC. (ENR7P),NO RESPONSE (ENR9P),TOTAL (ENRTOTP),PRIMARY ONLY (ENR1M),PRIMARY WITH UPPER PRIMARY (ENR2M),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (ENR3M),UPPER PRIMARY ONLY (ENR4M),UPPER PRIMARY WITH SEC./H.SEC (ENR5M),PRIMARY WITH UPPER PRIMARY SEC (ENR6M),UPPER PRIMARY WITH SEC. (ENR7M),NO RESPONSE (ENR9M),TOTAL (ENRTOTM),PRIMARY ONLY (ENR1GR),PRIMARY WITH UPPER PRIMARY (ENR2GR),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (ENR3GR),UPPER PRIMARY ONLY (ENR4GR),UPPER PRIMARY WITH SEC./H.SEC (ENR5GR),PRIMARY WITH UPPER PRIMARY SEC (ENR6GR),UPPER PRIMARY WITH SEC. (ENR7GR),NO RESPONSE (ENR9GR),TOTAL (ENRTOTGR),PRIMARY ONLY (ENR1PR),PRIMARY WITH UPPER PRIMARY (ENR2PR),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (ENR3PR),UPPER PRIMARY ONLY (ENR4PR),UPPER PRIMARY WITH SEC./H.SEC (ENR5PR),PRIMARY WITH UPPER PRIMARY SEC (ENR6PR),UPPER PRIMARY WITH SEC. (ENR7PR),NO RESPONSE (ENR9PR),TOTAL (ENRTOTPR),PRIMARY ONLY (TCH1G),PRIMARY WITH UPPER PRIMARY (TCH2G),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCH3G),UPPER PRIMARY ONLY (TCH4G),UPPER PRIMARY WITH SEC./H.SEC (TCH5G),PRIMARY WITH UPPER PRIMARY SEC (TCH6G),UPPER PRIMARY WITH SEC. (TCH7G),NO RESPONSE (TCH9G),TOTAL (TCHTOTG),PRIMARY ONLY (TCH1P),PRIMARY WITH UPPER PRIMARY (TCH2P),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCH3P),UPPER PRIMARY ONLY (TCH4P),UPPER PRIMARY WITH SEC./H.SEC (TCH5P),PRIMARY WITH UPPER PRIMARY SEC (TCH6P),UPPER PRIMARY WITH SEC. (TCH7P),NO RESPONSE (TCH9P),TOTAL (TCHTOTP),PRIMARY ONLY (TCH1M),PRIMARY WITH UPPER PRIMARY (TCH2M),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCH3M),UPPER PRIMARY ONLY (TCH4M),UPPER PRIMARY WITH SEC./H.SEC (TCH5M),PRIMARY WITH UPPER PRIMARY SEC (TCH6M),UPPER PRIMARY WITH SEC. (TCH7M),NO RESPONSE (TCH9M),TOTAL (TCHTOTM),PRIMARY ONLY (SCLS1),PRIMARY WITH UPPER PRIMARY (SCLS2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SCLS3),UPPER PRIMARY ONLY (SCLS4),UPPER PRIMARY WITH SEC./H.SEC (SCLS5),PRIMARY WITH UPPER PRIMARY SEC (SCLS6),UPPER PRIMARY WITH SEC. (SCLS7),TOTAL (SCLSTOT),PRIMARY ONLY (STCH1),PRIMARY WITH UPPER PRIMARY (STCH2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (STCH3),UPPER PRIMARY ONLY (STCH4),UPPER PRIMARY WITH SEC./H.SEC (STCH5),PRIMARY WITH UPPER PRIMARY SEC (STCH6),UPPER PRIMARY WITH SEC. (STCH7),TOTAL (STCHTOT),PRIMARY ONLY (ROAD1),PRIMARY WITH UPPER PRIMARY (ROAD2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (ROAD3),UPPER PRIMARY ONLY (ROAD4),UPPER PRIMARY WITH SEC./H.SEC (ROAD5),PRIMARY WITH UPPER PRIMARY SEC (ROAD6),UPPER PRIMARY WITH SEC. (ROAD7),TOTAL (ROADTOT),PRIMARY ONLY (SPLAY1),PRIMARY WITH UPPER PRIMARY (SPLAY2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SPLAY3),UPPER PRIMARY ONLY (SPLAY4),UPPER PRIMARY WITH SEC./H.SEC (SPLAY5),PRIMARY WITH UPPER PRIMARY SEC (SPLAY6),UPPER PRIMARY WITH SEC. (SPLAY7),TOTAL (SPLAYTOT),PRIMARY ONLY (SBNDR1),PRIMARY WITH UPPER PRIMARY (SBNDR2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SBNDR3),UPPER PRIMARY ONLY (SBNDR4),UPPER PRIMARY WITH SEC./H.SEC (SBNDR5),PRIMARY WITH UPPER PRIMARY SEC (SBNDR6),UPPER PRIMARY WITH SEC. (SBNDR7),TOTAL (SBNDRTOT),PRIMARY ONLY (SGTOIL1),PRIMARY WITH UPPER PRIMARY (SGTOIL2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SGTOIL3),UPPER PRIMARY ONLY (SGTOIL4),UPPER PRIMARY WITH SEC./H.SEC (SGTOIL5),PRIMARY WITH UPPER PRIMARY SEC (SGTOIL6),UPPER PRIMARY WITH SEC. (SGTOIL7),TOTAL (SGTOILTOT),PRIMARY ONLY (SBTOIL1),PRIMARY WITH UPPER PRIMARY (SBTOIL2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SBTOIL3),UPPER PRIMARY ONLY (SBTOIL4),UPPER PRIMARY WITH SEC./H.SEC (SBTOIL5),PRIMARY WITH UPPER PRIMARY SEC (SBTOIL6),UPPER PRIMARY WITH SEC. (SBTOIL7),TOTAL (SBTOILTOT),PRIMARY ONLY (SWAT1),PRIMARY WITH UPPER PRIMARY (SWAT2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SWAT3),UPPER PRIMARY ONLY (SWAT4),UPPER PRIMARY WITH SEC./H.SEC (SWAT5),PRIMARY WITH UPPER PRIMARY SEC (SWAT6),UPPER PRIMARY WITH SEC. (SWAT7),TOTAL (SWATTOT),PRIMARY ONLY (SELE1),PRIMARY WITH UPPER PRIMARY (SELE2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SELE3),UPPER PRIMARY ONLY (SELE4),UPPER PRIMARY WITH SEC./H.SEC (SELE5),PRIMARY WITH UPPER PRIMARY SEC (SELE6),UPPER PRIMARY WITH SEC. (SELE7),TOTAL (SELETOT),PRIMARY ONLY (SCOMP1),PRIMARY WITH UPPER PRIMARY (SCOMP2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SCOMP3),UPPER PRIMARY ONLY (SCOMP4),UPPER PRIMARY WITH SEC./H.SEC (SCOMP5),PRIMARY WITH UPPER PRIMARY SEC (SCOMP6),UPPER PRIMARY WITH SEC. (SCOMP7),TOTAL (SCOMPTOT),PRIMARY ONLY (SRAM1),PRIMARY WITH UPPER PRIMARY (SRAM2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SRAM3),UPPER PRIMARY ONLY (SRAM4),UPPER PRIMARY WITH SEC./H.SEC (SRAM5),PRIMARY WITH UPPER PRIMARY SEC (SRAM6),UPPER PRIMARY WITH SEC. (SRAM7),TOTAL (SRAMTOT),PRIMARY ONLY (SRAMN1),PRIMARY WITH UPPER PRIMARY (SRAMN2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SRAMN3),UPPER PRIMARY ONLY (SRAMN4),UPPER PRIMARY WITH SEC./H.SEC (SRAMN5),PRIMARY WITH UPPER PRIMARY SEC (SRAMN6),UPPER PRIMARY WITH SEC. (SRAMN7),TOTAL (SRAMNTOT),PRIMARY ONLY (ESTD1),PRIMARY WITH UPPER PRIMARY (ESTD2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (ESTD3),UPPER PRIMARY ONLY (ESTD4),UPPER PRIMARY WITH SEC./H.SEC (ESTD5),PRIMARY WITH UPPER PRIMARY SEC (ESTD6),UPPER PRIMARY WITH SEC. (ESTD7),TOTAL (ESTDTOT),PRIMARY ONLY (MDM1),PRIMARY WITH UPPER PRIMARY (MDM2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (MDM3),UPPER PRIMARY ONLY (MDM4),UPPER PRIMARY WITH SEC./H.SEC (MDM5),PRIMARY WITH UPPER PRIMARY SEC (MDM6),UPPER PRIMARY WITH SEC. (MDM7),TOTAL (MDMTOT),PRIMARY ONLY (KIT1),PRIMARY WITH UPPER PRIMARY (KIT2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (KIT3),UPPER PRIMARY ONLY (KIT4),UPPER PRIMARY WITH SEC./H.SEC (KIT5),PRIMARY WITH UPPER PRIMARY SEC (KIT6),UPPER PRIMARY WITH SEC. (KIT7),TOTAL (KITTOT),PRIMARY ONLY (KITS1),PRIMARY WITH UPPER PRIMARY (KITS2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (KITS3),UPPER PRIMARY ONLY (KITS4),UPPER PRIMARY WITH SEC./H.SEC (KITS5),PRIMARY WITH UPPER PRIMARY SEC (KITS6),UPPER PRIMARY WITH SEC. (KITS7),TOTAL (KITSTOT),PRIMARY ONLY (ENR501),PRIMARY WITH UPPER PRIMARY (ENR502),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (ENR503),UPPER PRIMARY ONLY (ENR504),UPPER PRIMARY WITH SEC./H.SEC (ENR505),PRIMARY WITH UPPER PRIMARY SEC (ENR506),UPPER PRIMARY WITH SEC. (ENR507),NO RESPONSE (ENR509),TOTAL (ENR50TOT),PRIMARY ONLY (SMC1),PRIMARY WITH UPPER PRIMARY (SMC2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SMC3),UPPER PRIMARY ONLY (SMC4),UPPER PRIMARY WITH SEC./H.SEC (SMC5),PRIMARY WITH UPPER PRIMARY SEC (SMC6),UPPER PRIMARY WITH SEC. (SMC7),TOTAL (SMCTOT),PRIMARY ONLY (CLS1),PRIMARY WITH UPPER PRIMARY (CLS2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (CLS3),UPPER PRIMARY ONLY (CLS4),UPPER PRIMARY WITH SEC./H.SEC (CLS5),PRIMARY WITH UPPER PRIMARY SEC (CLS6),UPPER PRIMARY WITH SEC. (CLS7),TOTAL (CLSTOT),PRIMARY ONLY (TCH1),PRIMARY WITH UPPER PRIMARY (TCH2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCH3),UPPER PRIMARY ONLY (TCH4),UPPER PRIMARY WITH SEC./H.SEC (TCH5),PRIMARY WITH UPPER PRIMARY SEC (TCH6),UPPER PRIMARY WITH SEC. (TCH7),TOTAL (TCHTOT),PRIMARY ONLY (TCHF1),PRIMARY WITH UPPER PRIMARY (TCHF2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHF3),UPPER PRIMARY ONLY (TCHF4),UPPER PRIMARY WITH SEC./H.SEC (TCHF5),PRIMARY WITH UPPER PRIMARY SEC (TCHF6),UPPER PRIMARY WITH SEC. (TCHF7),TOTAL (TCHFTOT),PRIMARY ONLY (TCHM1),PRIMARY WITH UPPER PRIMARY (TCHM2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHM3),UPPER PRIMARY ONLY (TCHM4),UPPER PRIMARY WITH SEC./H.SEC (TCHM5),PRIMARY WITH UPPER PRIMARY SEC (TCHM6),UPPER PRIMARY WITH SEC. (TCHM7),NO RESPONSE (TCHM9),PRIMARY ONLY (ENRG1),PRIMARY WITH UPPER PRIMARY (ENRG2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (ENRG3),UPPER PRIMARY ONLY (ENRG4),UPPER PRIMARY WITH SEC./H.SEC (ENRG5),PRIMARY WITH UPPER PRIMARY SEC (ENRG6),UPPER PRIMARY WITH SEC. (ENRG7),TOTAL (ENRGTOT),TOTAL SCHOOLS (PREP),TOTAL STUDENTS (PRESTD),TEACHERS WITH PROFESSIONAL QUALIFICATION : FEMALE (PPFTCH),TEACHERS WITH PROFESSIONAL QUALIFICATION : MALE (PPMTCH),TOTAL TEACHERS: MALE (PMTCH),TOTAL TEACHERS: FEMALE (PFTCH),PRIMARY ONLY (TCHSCM1),PRIMARY WITH UPPER PRIMARY (TCHSCM2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHSCM3),UPPER PRIMARY ONLY (TCHSCM4),UPPER PRIMARY WITH SEC./H.SEC (TCHSCM5),PRIMARY WITH UPPER PRIMARY SEC (TCHSCM6),UPPER PRIMARY WITH SEC. (TCHSCM7),PRIMARY ONLY (TCHSCF1),PRIMARY WITH UPPER PRIMARY (TCHSCF2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHSCF3),UPPER PRIMARY ONLY (TCHSCF4),UPPER PRIMARY WITH SEC./H.SEC (TCHSCF5),PRIMARY WITH UPPER PRIMARY SEC (TCHSCF6),UPPER PRIMARY WITH SEC. (TCHSCF7),PRIMARY ONLY (TCHSTM1),PRIMARY WITH UPPER PRIMARY (TCHSTM2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHSTM3),UPPER PRIMARY ONLY (TCHSTM4),UPPER PRIMARY WITH SEC./H.SEC (TCHSTM5),PRIMARY WITH UPPER PRIMARY SEC (TCHSTM6),UPPER PRIMARY WITH SEC. (TCHSTM7),PRIMARY ONLY (TCHSTF1),PRIMARY WITH UPPER PRIMARY (TCHSTF2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHSTF3),UPPER PRIMARY ONLY (TCHSTF4),UPPER PRIMARY WITH SEC./H.SEC (TCHSTF5),PRIMARY WITH UPPER PRIMARY SEC (TCHSTF6),UPPER PRIMARY WITH SEC. (TCHSTF7),PRIMARY ONLY (TCHOBCM1),PRIMARY WITH UPPER PRIMARY (TCHOBCM2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHOBCM3),UPPER PRIMARY ONLY (TCHOBCM4),UPPER PRIMARY WITH SEC./H.SEC (TCHOBCM5),PRIMARY WITH UPPER PRIMARY SEC (TCHOBCM6),UPPER PRIMARY WITH SEC. (TCHOBCM7),PRIMARY ONLY (TCHOBCF1),PRIMARY WITH UPPER PRIMARY (TCHOBCF2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHOBCF3),UPPER PRIMARY ONLY (TCHOBCF4),UPPER PRIMARY WITH SEC./H.SEC (TCHOBCF5),PRIMARY WITH UPPER PRIMARY SEC (TCHOBCF6),UPPER PRIMARY WITH SEC. (TCHOBCF7),PRIMARY ONLY (TCH TRNRM1),PRIMARY WITH UPPER PRIMARY (TCH TRNRM2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCH TRNRM3),UPPER PRIMARY ONLY (TCH TRNRM4),UPPER PRIMARY WITH SEC./H.SEC (TCH TRNRM5),PRIMARY WITH UPPER PRIMARY SEC (TCH TRNRM6),UPPER PRIMARY WITH SEC. (TCH TRNRM7),PRIMARY ONLY (TCH TRNRF1),PRIMARY WITH UPPER PRIMARY (TCH TRNRF2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCH TRNRF3),UPPER PRIMARY ONLY (TCH TRNRF4),UPPER PRIMARY WITH SEC./H.SEC (TCH TRNRF5),PRIMARY WITH UPPER PRIMARY SEC (TCH TRNRF6),UPPER PRIMARY WITH SEC. (TCH TRNRF7),REGULAR TEACHERS WITH PROFESSIONAL QUALIFICATION : MALE (PGRMTCH),REGULAR TEACHERS WITH PROFESSIONAL QUALIFICATION : FEMALE (PGRFTCH),TOTAL REGULAR TEACHERS: MALE (GRMTCH),TOTAL REGULAR TEACHERS: FEMALE (GRFTCH),CONTRACTUAL TEACHERS WITH PROFESSIONAL QUALIFICATION : MALE (PGCMTCH),CONTRACTUAL TEACHERS WITH PROFESSIONAL QUALIFICATION : FEMALE (PGCFTCH),TOTAL CONTRACTUAL TEACHERS: MALE (PCMTCH),TOTAL CONTRACTUAL TEACHERS: FEMALE (PCFTCH),GRADE 1 (C1 B),GRADE 2 (C2 B),GRADE 3 (C3 B),GRADE 4 (C4 B),GRADE 5 (C5 B),GRADE 6 (C6 B),GRADE 7 (C7 B),GRADE 8 (C8 B),GRADE 9 (C9 B),GRADE 1 (C1 G),GRADE 2 (C2 G),GRADE 3 (C3 G),GRADE 4 (C4 G),GRADE 5 (C5 G),GRADE 6 (C6 G),GRADE 7 (C7 G),GRADE 8 (C8 G),GRADE 9 (C9 G),(C15A),(C68A),GRADE 1 (C1 BD),GRADE 2 (C2 BD),GRADE 3 (C3 BD),GRADE 4 (C4 BD),GRADE 5 (C5 BD),GRADE 6 (C6 BD),GRADE 7 (C7 BD),GRADE 8 (C8 BD),GRADE 1 (C1 GD),GRADE 2 (C2 GD),GRADE 3 (C3 GD),GRADE 4 (C4 GD),GRADE 5 (C5 GD),GRADE 6 (C6 GD),GRADE 7 (C7 GD),GRADE 8 (C8 GD),GRADE 1 (C1 BR),GRADE 2 (C2 BR),GRADE 3 (C3 BR),GRADE 4 (C4 BR),GRADE 5 (C5 BR),GRADE 6 (C6 BR),GRADE 7 (C7 BR),GRADE 8 (C8 BR),GRADE 9 (C9 BR),GRADE 1 (C1 GR),GRADE 2 (C2 GR),GRADE 3 (C3 GR),GRADE 4 (C4 GR),GRADE 5 (C5 GR),GRADE 6 (C6 GR),GRADE 7 (C7 GR),GRADE 8 (C8 GR),GRADE 9 (C9 GR),TOTAL (SCPTOT),GIRLS (SCPTOT G),TOTAL (SCUTOT),GIRLS (SCUTOT G),TOTAL (STPTOT),GIRLS (STPTOT G),TOTAL (STUTOT),GIRLS (STUTOT G),TOTAL (OBPTOT),GIRLS (OBUTOT),TOTAL (OBPTOT G),GIRLS (OBUTOT G),TOTAL (MUPTOT),GIRLS (MUUTOT),TOTAL (MUPTOT G),GIRLS (MUUTOT G),BLIND (BLC1),LOW VISION (LVC1),HEARING IMPAIRMENT (HEC1),SPEECH IMPAIRMENT (SPC1),LOCOMOTOR IMPAIRMENT (LOC1),MENTAL RETARDATION (MEC1),LEARNING DISABILITY (LEC1),CEREBRAL PALSY (CPC1),AUTISM (AUC1),MULTIPLE (MUC1),BLIND (BLC2),LOW VISION (LVC2),HEARING IMPAIRMENT (HEC2),SPEECH IMPAIRMENT (SPC2),LOCOMOTOR IMPAIRMENT (LOC2),MENTAL RETARDATION (MEC2),LEARNING DISABILITY (LEC2),CEREBRAL PALSY (CPC2),AUTISM (AUC2),MULTIPLE (MUC2),BLIND (BLC3),LOW VISION (LVC3),HEARING IMPAIRMENT (HEC3),SPEECH IMPAIRMENT (SPC3),LOCOMOTOR IMPAIRMENT (LOC3),MENTAL RETARDATION (MEC3),LEARNING DISABILITY (LEC3),CEREBRAL PALSY (CPC3),AUTISM (AUC3),MULTIPLE (MUC3),BLIND (BLC4),LOW VISION (LVC4),HEARING IMPAIRMENT (HEC4),SPEECH IMPAIRMENT (SPC4),LOCOMOTOR IMPAIRMENT (LOC4),MENTAL RETARDATION (MEC4),LEARNING DISABILITY (LEC4),CEREBRAL PALSY (CPC4),AUTISM (AUC4),MULTIPLE (MUC4),BLIND (BLC5),LOW VISION (LVC5),HEARING IMPAIRMENT (HEC5),SPEECH IMPAIRMENT (SPC5),LOCOMOTOR IMPAIRMENT (LOC5),MENTAL RETARDATION (MEC5),LEARNING DISABILITY (LEC5),CEREBRAL PALSY (CPC5),AUTISM (AUC5),MULTIPLE (MUC5),BLIND (BLC6),LOW VISION (LVC6),HEARING IMPAIRMENT (HEC6),SPEECH IMPAIRMENT (SPC6),LOCOMOTOR IMPAIRMENT (LOC6),MENTAL RETARDATION (MEC6),LEARNING DISABILITY (LEC6),CEREBRAL PALSY (CPC6),AUTISM (AUC6),MULTIPLE (MUC6),BLIND (BLC7),LOW VISION (LVC7),HEARING IMPAIRMENT (HEC7),SPEECH IMPAIRMENT (SPC7),LOCOMOTOR IMPAIRMENT (LOC7),MENTAL RETARDATION (MEC7),LEARNING DISABILITY (LEC7),CEREBRAL PALSY (CPC7),AUTISM (AUC7),MULTIPLE (MUC7),BLIND (BLC8),LOW VISION (LVC8),HEARING IMPAIRMENT (HEC8),SPEECH IMPAIRMENT (SPC8),LOCOMOTOR IMPAIRMENT (LOC8),MENTAL RETARDATION (MEC8),LEARNING DISABILITY (LEC8),CEREBRAL PALSY (CPC8),AUTISM (AUC8),MULTIPLE (MUC8),PRIMARY ONLY (TOTCLGD1G),PRIMARY WITH UPPER PRIMARY (TOTCLGD2G),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TOTCLGD3G),UPPER PRIMARY ONLY (TOTCLGD4G),UPPER PRIMARY WITH SEC./H.SEC (TOTCLGD5G),PRIMARY WITH UPPER PRIMARY SEC (TOTCLGD6G),UPPER PRIMARY WITH SEC. (TOTCLGD7G),PRIMARY ONLY (TOTCLMI1G),PRIMARY WITH UPPER PRIMARY (TOTCLMI2G),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TOTCLMI3G),UPPER PRIMARY ONLY (TOTCLMI4G),UPPER PRIMARY WITH SEC./H.SEC (TOTCLMI5G),PRIMARY WITH UPPER PRIMARY SEC (TOTCLMI6G),UPPER PRIMARY WITH SEC. (TOTCLMI7G),PRIMARY ONLY (TOTCLMJ1G),PRIMARY WITH UPPER PRIMARY (TOTCLMJ2G),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TOTCLMJ3G),UPPER PRIMARY ONLY (TOTCLMJ4G),UPPER PRIMARY WITH SEC./H.SEC (TOTCLMJ5G),PRIMARY WITH UPPER PRIMARY SEC (TOTCLMJ6G),UPPER PRIMARY WITH SEC. (TOTCLMJ7G),(TOTCLOT1G),(TOTCLOT2G),(TOTCLOT3G),(TOTCLOT4G),(TOTCLOT5G),(TOTCLOT6G),(TOTCLOT7G),PRIMARY ONLY (TCHBS1),PRIMARY WITH UPPER PRIMARY (TCHBS2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHBS3),UPPER PRIMARY ONLY (TCHBS4),UPPER PRIMARY WITH SEC./H.SEC (TCHBS5),PRIMARY WITH UPPER PRIMARY SEC (TCHBS6),UPPER PRIMARY WITH SEC. (TCHBS7),PRIMARY ONLY (TCHSEC1),PRIMARY WITH UPPER PRIMARY (TCHSEC2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHSEC3),UPPER PRIMARY ONLY (TCHSEC4),UPPER PRIMARY WITH SEC./H.SEC (TCHSEC5),PRIMARY WITH UPPER PRIMARY SEC (TCHSEC6),UPPER PRIMARY WITH SEC. (TCHSEC7),PRIMARY ONLY (TCHHS1),PRIMARY WITH UPPER PRIMARY (TCHHS2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHHS3),UPPER PRIMARY ONLY (TCHHS4),UPPER PRIMARY WITH SEC./H.SEC (TCHHS5),PRIMARY WITH UPPER PRIMARY SEC (TCHHS6),UPPER PRIMARY WITH SEC. (TCHHS7),PRIMARY ONLY (TCHGD1),PRIMARY WITH UPPER PRIMARY (TCHGD2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHGD3),UPPER PRIMARY ONLY (TCHGD4),UPPER PRIMARY WITH SEC./H.SEC (TCHGD5),PRIMARY WITH UPPER PRIMARY SEC (TCHGD6),UPPER PRIMARY WITH SEC. (TCHGD7),PRIMARY ONLY (TCHPG1),PRIMARY WITH UPPER PRIMARY (TCHPG2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHPG3),UPPER PRIMARY ONLY (TCHPG4),UPPER PRIMARY WITH SEC./H.SEC (TCHPG5),PRIMARY WITH UPPER PRIMARY SEC (TCHPG6),UPPER PRIMARY WITH SEC. (TCHPG7),PRIMARY ONLY (TCHMD1),PRIMARY WITH UPPER PRIMARY (TCHMD2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHMD3),UPPER PRIMARY ONLY (TCHMD4),UPPER PRIMARY WITH SEC./H.SEC (TCHMD5),PRIMARY WITH UPPER PRIMARY SEC (TCHMD6),UPPER PRIMARY WITH SEC. (TCHMD7),PRIMARY ONLY (TCHPD1),PRIMARY WITH UPPER PRIMARY (TCHPD2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHPD3),UPPER PRIMARY ONLY (TCHPD4),UPPER PRIMARY WITH SEC./H.SEC (TCHPD5),PRIMARY WITH UPPER PRIMARY SEC (TCHPD6),UPPER PRIMARY WITH SEC. (TCHPD7),PRIMARY ONLY (TCHNR1),PRIMARY WITH UPPER PRIMARY (TCHNR2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHNR3),UPPER PRIMARY ONLY (TCHNR4),UPPER PRIMARY WITH SEC./H.SEC (TCHNR5),PRIMARY WITH UPPER PRIMARY SEC (TCHNR6),UPPER PRIMARY WITH SEC. (TCHNR7),BELOW SECONDARY (TCHCON1),SECONDARY (TCHCON2),HIGHER SECONDARY (TCHCON3),GRADUATE (TCHCON4),POST GRADUATE (TCHCON5),M PHIL./ PH.D. (TCHCON67),POST DOCTORATE (TCHCON8),NO RESPONSE (TCHCON9),PRIMARY ONLY (TCHN1),PRIMARY WITH UPPER PRIMARY (TCHN2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHN3),UPPER PRIMARY ONLY (TCHN4),UPPER PRIMARY WITH SEC./H.SEC (TCHN5),PRIMARY WITH UPPER PRIMARY SEC (TCHN6),UPPER PRIMARY WITH SEC. (TCHN7),PRIMARY ONLY (TCHCM1),PRIMARY WITH UPPER P

# Combined census , school and gdp data at district level

In [6]:
#CenElemGdp = [census,eleschl,dataGDP]
CenElem    = pd.merge(census,eleschl,  on=['STATE NAME','DISTRICT NAME'],how='left')
CenElemGDP = pd.merge(CenElem,dataGDP, on=['STATE NAME','DISTRICT NAME'],how='left')
CenElemGDP.head()

,District code,STATE NAME,DISTRICT NAME,Population,Male,Female,Literate,Male_Literate,Female_Literate,SC,Male_SC,Female_SC,ST,Male_ST,Female_ST,Workers,Male_Workers,Female_Workers,Main_Workers,Marginal_Workers,Non_Workers,Cultivator_Workers,Agricultural_Workers,Household_Workers,Other_Workers,Hindus,Muslims,Christians,Sikhs,Buddhists,Jains,Others_Religions,Religion_Not_Stated,LPG_or_PNG_Households,Housholds_with_Electric_Lighting,Households_with_Internet,Households_with_Computer,Rural_Households,Urban_Households,Households,Below_Primary_Education,Primary_Education,Middle_Education,Secondary_Education,Higher_Education,Graduate_Education,Other_Education,Literate_Education,Illiterate_Education,Total_Education,Age_Group_0_29,Age_Group_30_49,Age_Group_50,Age not stated,Households_with_Bicycle,Households_with_Car_Jeep_Van,Households_with_Radio_Transistor,Households_with_Scooter_Motorcycle_Moped,Households_with_Telephone_Mobile_Phone_Landline_only,Households_with_Telephone_Mobile_Phone_Mobile_only,Households_with_TV_Computer_Laptop_Telephone_mobile_phone_and_Scooter_Car,Households_with_Television,Households_with_Telephone_Mobile_Phone,Households_with_Telephone_Mobile_Phone_Both,Condition_of_occupied_census_houses_Dilapidated_Households,Households_with_separate_kitchen_Cooking_inside_house,Having_bathing_facility_Total_Households,Having_latrine_facility_within_the_premises_Total_Households,Ownership_Owned_Households,Ownership_Rented_Households,Type_of_bathing_facility_Enclosure_without_roof_Households,Type_of_fuel_used_for_cooking_Any_other_Households,Type_of_latrine_facility_Pit_latrine_Households,Type_of_latrine_facility_Other_latrine_Households,Type_of_latrine_facility_Night_soil_disposed_into_open_drain_Households,Type_of_latrine_facility_Flush_pour_flush_latrine_connected_to_other_system_Households,Not_having_bathing_facility_within_the_premises_Total_Households,Not_having_latrine_facility_within_the_premises_Alternative_source_Open_Households,Main_source_of_drinking_water_Un_covered_well_Households,Main_source_of_drinking_water_Handpump_Tubewell_Borewell_Households,Main_source_of_drinking_water_Spring_Households,Main_source_of_drinking_water_River_Canal_Households,Main_source_of_drinking_water_Other_sources_Households,Main_source_of_drinking_water_Other_sources_Spring_River_Canal_Tank_Pond_Lake_Other_sources__Households,Location_of_drinking_water_source_Near_the_premises_Households,Location_of_drinking_water_source_Within_the_premises_Households,Main_source_of_drinking_water_Tank_Pond_Lake_Households,Main_source_of_drinking_water_Tapwater_Households,Main_source_of_drinking_water_Tubewell_Borehole_Households,Household_size_1_person_Households,Household_size_2_persons_Households,Household_size_1_to_2_persons,Household_size_3_persons_Households,Household_size_3_to_5_persons_Households,Household_size_4_persons_Households,Household_size_5_persons_Households,Household_size_6_8_persons_Households,Household_size_9_persons_and_above_Households,Location_of_drinking_water_source_Away_Households,Married_couples_1_Households,Married_couples_2_Households,Married_couples_3_Households,Married_couples_3_or_more_Households,Married_couples_4_Households,Married_couples_5__Households,Married_couples_None_Households,Power_Parity_Less_than_Rs_45000,Power_Parity_Rs_45000_90000,Power_Parity_Rs_90000_150000,Power_Parity_Rs_45000_150000,Power_Parity_Rs_150000_240000,Power_Parity_Rs_240000_330000,Power_Parity_Rs_150000_330000,Power_Parity_Rs_330000_425000,Power_Parity_Rs_425000_545000,Power_Parity_Rs_330000_545000,Power_Parity_Above_Rs_545000,Total_Power_Parity,Unnamed: 0,YEAR,TOTAL POULATION,PERCENTAGE URBAN POPULATION,0-6 POPULATION,GROWTH RATE,SEX RATIO,PERCENTAGE SC POPULATION,PERCENTAGE ST POPULATION,OVERALL LITERACY,FEMALE LITERACY,MALE LITERACY,AREA (SQ. KM) (AREA SQKM),AGE GROUP 6 TO 10 (TOT 6 10 15),AGE GROUP 11 TO 13 (TOT 11 13 15),PRIMARY ONLY (SCH1),PRIMARY WITH UPPER PRIMARY (SCH2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SCH3),UPPER PRIMARY ONLY (SCH4),UPPER PRIMARY WITH SEC./H.SEC (SCH5),PRIMARY WITH UPPER PRIMARY SEC (SCH6),UPPER PRIMARY WITH SEC. (SCH7),NO RESPONSE (SCH9),TOTAL (SCHTOT),PRIMARY ONLY (SCH1G),PRIMARY WITH UPPER PRIMARY (SCH2G),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SCH3G),UPPER PRIMARY ONLY (SCH4G),UPPER PRIMARY WITH SEC./H.SEC (SCH5G),PRIMARY WITH UPPER PRIMARY SEC (SCH6G),UPPER PRIMARY WITH SEC. (SCH7G),NO RESPONSE (SCH9G),TOTAL (SCHTOTG),PRIMARY ONLY (SCH1P),PRIMARY WITH UPPER PRIMARY (SCH2P),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SCH3P),UPPER PRIMARY ONLY (SCH4P),UPPER PRIMARY WITH SEC./H.SEC (SCH5P),PRIMARY WITH UPPER PRIMARY SEC (SCH6P),UPPER PRIMARY WITH SEC. (SCH7P),NO RESPONSE (SCH9P),TOTAL (SCHTOTP),PRIMARY ONLY (SCH1M),PRIMARY WITH UPPER PRIMARY (SCH2M),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SCH3M),UPPER PRIMARY ONLY (SCH4M),UPPER PRIMARY WITH SEC./H.SEC (SCH5M),PRIMARY WITH UPPER PRIMARY SEC (SCH6M),UPPER PRIMARY WITH SEC. (SCH7M),NO RESPONSE (SCH9M),TOTAL (SCHTOTM),PRIMARY ONLY (SCH1GR),PRIMARY WITH UPPER PRIMARY (SCH2GR),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SCH3GR),UPPER PRIMARY ONLY (SCH4GR),UPPER PRIMARY WITH SEC./H.SEC (SCH5GR),PRIMARY WITH UPPER PRIMARY SEC (SCH6GR),UPPER PRIMARY WITH SEC. (SCH7GR),NO RESPONSE (SCH9GR),TOTAL (SCHTOTGR),PRIMARY ONLY (SCH1GA),PRIMARY WITH UPPER PRIMARY (SCH2GA),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SCH3GA),UPPER PRIMARY ONLY (SCH4GA),UPPER PRIMARY WITH SEC./H.SEC (SCH5GA),PRIMARY WITH UPPER PRIMARY SEC (SCH6GA),UPPER PRIMARY WITH SEC. (SCH7GA),NO RESPONSE (SCH9GA),TOTAL (SCHTOTGA),PRIMARY ONLY (SCH1PR),PRIMARY WITH UPPER PRIMARY (SCH2PR),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SCH3PR),UPPER PRIMARY ONLY (SCH4PR),UPPER PRIMARY WITH SEC./H.SEC (SCH5PR),PRIMARY WITH UPPER PRIMARY SEC (SCH6PR),UPPER PRIMARY WITH SEC. (SCH7PR),NO RESPONSE (SCH9PR),TOTAL (SCHTOTPR),PRIMARY ONLY (SCHBOY1),PRIMARY WITH UPPER PRIMARY (SCHBOY2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SCHBOY3),UPPER PRIMARY ONLY (SCHBOY4),UPPER PRIMARY WITH SEC./H.SEC (SCHBOY5),PRIMARY WITH UPPER PRIMARY SEC (SCHBOY6),UPPER PRIMARY WITH SEC. (SCHBOY7),NO RESPONSE (SCHBOY9),TOTAL (SCHBOYTOT),PRIMARY ONLY (SCHGIR1),PRIMARY WITH UPPER PRIMARY (SCHGIR2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SCHGIR3),UPPER PRIMARY ONLY (SCHGIR4),UPPER PRIMARY WITH SEC./H.SEC (SCHGIR5),PRIMARY WITH UPPER PRIMARY SEC (SCHGIR6),UPPER PRIMARY WITH SEC. (SCHGIR7),NO RESPONSE (SCHGIR9),TOTAL (SCHGIRTOT),PRIMARY ONLY (ENR1),PRIMARY WITH UPPER PRIMARY (ENR2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (ENR3),UPPER PRIMARY ONLY (ENR4),UPPER PRIMARY WITH SEC./H.SEC (ENR5),PRIMARY WITH UPPER PRIMARY SEC (ENR6),UPPER PRIMARY WITH SEC. (ENR7),NO RESPONSE (ENR9),TOTAL (ENRTOT),PRIMARY ONLY (ENR1G),PRIMARY WITH UPPER PRIMARY (ENR2G),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (ENR3G),UPPER PRIMARY ONLY (ENR4G),UPPER PRIMARY WITH SEC./H.SEC (ENR5G),PRIMARY WITH UPPER PRIMARY SEC (ENR6G),UPPER PRIMARY WITH SEC. (ENR7G),NO RESPONSE (ENR9G),TOTAL (ENRTOTG),PRIMARY ONLY (ENR1P),PRIMARY WITH UPPER PRIMARY (ENR2P),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (ENR3P),UPPER PRIMARY ONLY (ENR4P),UPPER PRIMARY WITH SEC./H.SEC (ENR5P),PRIMARY WITH UPPER PRIMARY SEC (ENR6P),UPPER PRIMARY WITH SEC. (ENR7P),NO RESPONSE (ENR9P),TOTAL (ENRTOTP),PRIMARY ONLY (ENR1M),PRIMARY WITH UPPER PRIMARY (ENR2M),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (ENR3M),UPPER PRIMARY ONLY (ENR4M),UPPER PRIMARY WITH SEC./H.SEC (ENR5M),PRIMARY WITH UPPER PRIMARY SEC (ENR6M),UPPER PRIMARY WITH SEC. (ENR7M),NO RESPONSE (ENR9M),TOTAL (ENRTOTM),PRIMARY ONLY (ENR1GR),PRIMARY WITH UPPER PRIMARY (ENR2GR),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (ENR3GR),UPPER PRIMARY ONLY (ENR4GR),UPPER PRIMARY WITH SEC./H.SEC (ENR5GR),PRIMARY WITH UPPER PRIMARY SEC (ENR6GR),UPPER PRIMARY WITH SEC. (ENR7GR),NO RESPONSE (ENR9GR),TOTAL (ENRTOTGR),PRIMARY ONLY (ENR1PR),PRIMARY WITH UPPER PRIMARY (ENR2PR),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (ENR3PR),UPPER PRIMARY ONLY (ENR4PR),UPPER PRIMARY WITH SEC./H.SEC (ENR5PR),PRIMARY WITH UPPER PRIMARY SEC (ENR6PR),UPPER PRIMARY WITH SEC. (ENR7PR),NO RESPONSE (ENR9PR),TOTAL (ENRTOTPR),PRIMARY ONLY (TCH1G),PRIMARY WITH UPPER PRIMARY (TCH2G),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCH3G),UPPER PRIMARY ONLY (TCH4G),UPPER PRIMARY WITH SEC./H.SEC (TCH5G),PRIMARY WITH UPPER PRIMARY SEC (TCH6G),UPPER PRIMARY WITH SEC. (TCH7G),NO RESPONSE (TCH9G),TOTAL (TCHTOTG),PRIMARY ONLY (TCH1P),PRIMARY WITH UPPER PRIMARY (TCH2P),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCH3P),UPPER PRIMARY ONLY (TCH4P),UPPER PRIMARY WITH SEC./H.SEC (TCH5P),PRIMARY WITH UPPER PRIMARY SEC (TCH6P),UPPER PRIMARY WITH SEC. (TCH7P),NO RESPONSE (TCH9P),TOTAL (TCHTOTP),PRIMARY ONLY (TCH1M),PRIMARY WITH UPPER PRIMARY (TCH2M),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCH3M),UPPER PRIMARY ONLY (TCH4M),UPPER PRIMARY WITH SEC./H.SEC (TCH5M),PRIMARY WITH UPPER PRIMARY SEC (TCH6M),UPPER PRIMARY WITH SEC. (TCH7M),NO RESPONSE (TCH9M),TOTAL (TCHTOTM),PRIMARY ONLY (SCLS1),PRIMARY WITH UPPER PRIMARY (SCLS2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SCLS3),UPPER PRIMARY ONLY (SCLS4),UPPER PRIMARY WITH SEC./H.SEC (SCLS5),PRIMARY WITH UPPER PRIMARY SEC (SCLS6),UPPER PRIMARY WITH SEC. (SCLS7),TOTAL (SCLSTOT),PRIMARY ONLY (STCH1),PRIMARY WITH UPPER PRIMARY (STCH2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (STCH3),UPPER PRIMARY ONLY (STCH4),UPPER PRIMARY WITH SEC./H.SEC (STCH5),PRIMARY WITH UPPER PRIMARY SEC (STCH6),UPPER PRIMARY WITH SEC. (STCH7),TOTAL (STCHTOT),PRIMARY ONLY (ROAD1),PRIMARY WITH UPPER PRIMARY (ROAD2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (ROAD3),UPPER PRIMARY ONLY (ROAD4),UPPER PRIMARY WITH SEC./H.SEC (ROAD5),PRIMARY WITH UPPER PRIMARY SEC (ROAD6),UPPER PRIMARY WITH SEC. (ROAD7),TOTAL (ROADTOT),PRIMARY ONLY (SPLAY1),PRIMARY WITH UPPER PRIMARY (SPLAY2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SPLAY3),UPPER PRIMARY ONLY (SPLAY4),UPPER PRIMARY WITH SEC./H.SEC (SPLAY5),PRIMARY WITH UPPER PRIMARY SEC (SPLAY6),UPPER PRIMARY WITH SEC. (SPLAY7),TOTAL (SPLAYTOT),PRIMARY ONLY (SBNDR1),PRIMARY WITH UPPER PRIMARY (SBNDR2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SBNDR3),UPPER PRIMARY ONLY (SBNDR4),UPPER PRIMARY WITH SEC./H.SEC (SBNDR5),PRIMARY WITH UPPER PRIMARY SEC (SBNDR6),UPPER PRIMARY WITH SEC. (SBNDR7),TOTAL (SBNDRTOT),PRIMARY ONLY (SGTOIL1),PRIMARY WITH UPPER PRIMARY (SGTOIL2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SGTOIL3),UPPER PRIMARY ONLY (SGTOIL4),UPPER PRIMARY WITH SEC./H.SEC (SGTOIL5),PRIMARY WITH UPPER PRIMARY SEC (SGTOIL6),UPPER PRIMARY WITH SEC. (SGTOIL7),TOTAL (SGTOILTOT),PRIMARY ONLY (SBTOIL1),PRIMARY WITH UPPER PRIMARY (SBTOIL2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SBTOIL3),UPPER PRIMARY ONLY (SBTOIL4),UPPER PRIMARY WITH SEC./H.SEC (SBTOIL5),PRIMARY WITH UPPER PRIMARY SEC (SBTOIL6),UPPER PRIMARY WITH SEC. (SBTOIL7),TOTAL (SBTOILTOT),PRIMARY ONLY (SWAT1),PRIMARY WITH UPPER PRIMARY (SWAT2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SWAT3),UPPER PRIMARY ONLY (SWAT4),UPPER PRIMARY WITH SEC./H.SEC (SWAT5),PRIMARY WITH UPPER PRIMARY SEC (SWAT6),UPPER PRIMARY WITH SEC. (SWAT7),TOTAL (SWATTOT),PRIMARY ONLY (SELE1),PRIMARY WITH UPPER PRIMARY (SELE2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SELE3),UPPER PRIMARY ONLY (SELE4),UPPER PRIMARY WITH SEC./H.SEC (SELE5),PRIMARY WITH UPPER PRIMARY SEC (SELE6),UPPER PRIMARY WITH SEC. (SELE7),TOTAL (SELETOT),PRIMARY ONLY (SCOMP1),PRIMARY WITH UPPER PRIMARY (SCOMP2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SCOMP3),UPPER PRIMARY ONLY (SCOMP4),UPPER PRIMARY WITH SEC./H.SEC (SCOMP5),PRIMARY WITH UPPER PRIMARY SEC (SCOMP6),UPPER PRIMARY WITH SEC. (SCOMP7),TOTAL (SCOMPTOT),PRIMARY ONLY (SRAM1),PRIMARY WITH UPPER PRIMARY (SRAM2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SRAM3),UPPER PRIMARY ONLY (SRAM4),UPPER PRIMARY WITH SEC./H.SEC (SRAM5),PRIMARY WITH UPPER PRIMARY SEC (SRAM6),UPPER PRIMARY WITH SEC. (SRAM7),TOTAL (SRAMTOT),PRIMARY ONLY (SRAMN1),PRIMARY WITH UPPER PRIMARY (SRAMN2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SRAMN3),UPPER PRIMARY ONLY (SRAMN4),UPPER PRIMARY WITH SEC./H.SEC (SRAMN5),PRIMARY WITH UPPER PRIMARY SEC (SRAMN6),UPPER PRIMARY WITH SEC. (SRAMN7),TOTAL (SRAMNTOT),PRIMARY ONLY (ESTD1),PRIMARY WITH UPPER PRIMARY (ESTD2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (ESTD3),UPPER PRIMARY ONLY (ESTD4),UPPER PRIMARY WITH SEC./H.SEC (ESTD5),PRIMARY WITH UPPER PRIMARY SEC (ESTD6),UPPER PRIMARY WITH SEC. (ESTD7),TOTAL (ESTDTOT),PRIMARY ONLY (MDM1),PRIMARY WITH UPPER PRIMARY (MDM2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (MDM3),UPPER PRIMARY ONLY (MDM4),UPPER PRIMARY WITH SEC./H.SEC (MDM5),PRIMARY WITH UPPER PRIMARY SEC (MDM6),UPPER PRIMARY WITH SEC. (MDM7),TOTAL (MDMTOT),PRIMARY ONLY (KIT1),PRIMARY WITH UPPER PRIMARY (KIT2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (KIT3),UPPER PRIMARY ONLY (KIT4),UPPER PRIMARY WITH SEC./H.SEC (KIT5),PRIMARY WITH UPPER PRIMARY SEC (KIT6),UPPER PRIMARY WITH SEC. (KIT7),TOTAL (KITTOT),PRIMARY ONLY (KITS1),PRIMARY WITH UPPER PRIMARY (KITS2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (KITS3),UPPER PRIMARY ONLY (KITS4),UPPER PRIMARY WITH SEC./H.SEC (KITS5),PRIMARY WITH UPPER PRIMARY SEC (KITS6),UPPER PRIMARY WITH SEC. (KITS7),TOTAL (KITSTOT),PRIMARY ONLY (ENR501),PRIMARY WITH UPPER PRIMARY (ENR502),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (ENR503),UPPER PRIMARY ONLY (ENR504),UPPER PRIMARY WITH SEC./H.SEC (ENR505),PRIMARY WITH UPPER PRIMARY SEC (ENR506),UPPER PRIMARY WITH SEC. (ENR507),NO RESPONSE (ENR509),TOTAL (ENR50TOT),PRIMARY ONLY (SMC1),PRIMARY WITH UPPER PRIMARY (SMC2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SMC3),UPPER PRIMARY ONLY (SMC4),UPPER PRIMARY WITH SEC./H.SEC (SMC5),PRIMARY WITH UPPER PRIMARY SEC (SMC6),UPPER PRIMARY WITH SEC. (SMC7),TOTAL (SMCTOT),PRIMARY ONLY (CLS1),PRIMARY WITH UPPER PRIMARY (CLS2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (CLS3),UPPER PRIMARY ONLY (CLS4),UPPER PRIMARY WITH SEC./H.SEC (CLS5),PRIMARY WITH UPPER PRIMARY SEC (CLS6),UPPER PRIMARY WITH SEC. (CLS7),TOTAL (CLSTOT),PRIMARY ONLY (TCH1),PRIMARY WITH UPPER PRIMARY (TCH2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCH3),UPPER PRIMARY ONLY (TCH4),UPPER PRIMARY WITH SEC./H.SEC (TCH5),PRIMARY WITH UPPER PRIMARY SEC (TCH6),UPPER PRIMARY WITH SEC. (TCH7),TOTAL (TCHTOT),PRIMARY ONLY (TCHF1),PRIMARY WITH UPPER PRIMARY (TCHF2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHF3),UPPER PRIMARY ONLY (TCHF4),UPPER PRIMARY WITH SEC./H.SEC (TCHF5),PRIMARY WITH UPPER PRIMARY SEC (TCHF6),UPPER PRIMARY WITH SEC. (TCHF7),TOTAL (TCHFTOT),PRIMARY ONLY (TCHM1),PRIMARY WITH UPPER PRIMARY (TCHM2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHM3),UPPER PRIMARY ONLY (TCHM4),UPPER PRIMARY WITH SEC./H.SEC (TCHM5),PRIMARY WITH UPPER PRIMARY SEC (TCHM6),UPPER PRIMARY WITH SEC. (TCHM7),NO RESPONSE (TCHM9),PRIMARY ONLY (ENRG1),PRIMARY WITH UPPER PRIMARY (ENRG2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (ENRG3),UPPER PRIMARY ONLY (ENRG4),UPPER PRIMARY WITH SEC./H.SEC (ENRG5),PRIMARY WITH UPPER PRIMARY SEC (ENRG6),UPPER PRIMARY WITH SEC. (ENRG7),TOTAL (ENRGTOT),TOTAL SCHOOLS (PREP),TOTAL STUDENTS (PRESTD),TEACHERS WITH PROFESSIONAL QUALIFICATION : FEMALE (PPFTCH),TEACHERS WITH PROFESSIONAL QUALIFICATION : MALE (PPMTCH),TOTAL TEACHERS: MALE (PMTCH),TOTAL TEACHERS: FEMALE (PFTCH),PRIMARY ONLY (TCHSCM1),PRIMARY WITH UPPER PRIMARY (TCHSCM2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHSCM3),UPPER PRIMARY ONLY (TCHSCM4),UPPER PRIMARY WITH SEC./H.SEC (TCHSCM5),PRIMARY WITH UPPER PRIMARY SEC (TCHSCM6),UPPER PRIMARY WITH SEC. (TCHSCM7),PRIMARY ONLY (TCHSCF1),PRIMARY WITH UPPER PRIMARY (TCHSCF2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHSCF3),UPPER PRIMARY ONLY (TCHSCF4),UPPER PRIMARY WITH SEC./H.SEC (TCHSCF5),PRIMARY WITH UPPER PRIMARY SEC (TCHSCF6),UPPER PRIMARY WITH SEC. (TCHSCF7),PRIMARY ONLY (TCHSTM1),PRIMARY WITH UPPER PRIMARY (TCHSTM2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHSTM3),UPPER PRIMARY ONLY (TCHSTM4),UPPER PRIMARY WITH SEC./H.SEC (TCHSTM5),PRIMARY WITH UPPER PRIMARY SEC (TCHSTM6),UPPER PRIMARY WITH SEC. (TCHSTM7),PRIMARY ONLY (TCHSTF1),PRIMARY WITH UPPER PRIMARY (TCHSTF2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHSTF3),UPPER PRIMARY ONLY (TCHSTF4),UPPER PRIMARY WITH SEC./H.SEC (TCHSTF5),PRIMARY WITH UPPER PRIMARY SEC (TCHSTF6),UPPER PRIMARY WITH SEC. (TCHSTF7),PRIMARY ONLY (TCHOBCM1),PRIMARY WITH UPPER PRIMARY (TCHOBCM2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHOBCM3),UPPER PRIMARY ONLY (TCHOBCM4),UPPER PRIMARY WITH SEC./H.SEC (TCHOBCM5),PRIMARY WITH UPPER PRIMARY SEC (TCHOBCM6),UPPER PRIMARY WITH SEC. (TCHOBCM7),PRIMARY ONLY (TCHOBCF1),PRIMARY WITH UPPER PRIMARY (TCHOBCF2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHOBCF3),UPPER PRIMARY ONLY (TCHOBCF4),UPPER PRIMARY WITH SEC./H.SEC (TCHOBCF5),PRIMARY WITH UPPER PRIMARY SEC (TCHOBCF6),UPPER PRIMARY WITH SEC. (TCHOBCF7),PRIMARY ONLY (TCH TRNRM1),PRIMARY WITH UPPER PRIMARY (TCH TRNRM2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCH TRNRM3),UPPER PRIMARY ONLY (TCH TRNRM4),UPPER PRIMARY WITH SEC./H.SEC (TCH TRNRM5),PRIMARY WITH UPPER PRIMARY SEC (TCH TRNRM6),UPPER PRIMARY WITH SEC. (TCH TRNRM7),PRIMARY ONLY (TCH TRNRF1),PRIMARY WITH UPPER PRIMARY (TCH TRNRF2),PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCH TRNRF3),UPPER PRIMARY ONLY (TCH TRNRF4),UPPER PRIMARY WITH SEC./H.SEC (TCH TRNRF5),PRIMARY WITH UPPER PRIMARY SEC (TCH TRNRF6),UPPER PRIMARY WITH SEC. (TCH TRNRF7),REGULAR TEACHERS WITH PROFESSIONAL QUALIFICATION : MALE (PGRMTCH),REGULAR TEACHERS WITH PROFESSIONAL QUALIFICATION : FEMALE (PGRFTCH),TOTAL REGULAR TEACHERS: MALE (GRMTCH),TOTAL REGULAR TEACHERS: FEMALE (GRFTCH),CONTRACTUAL TEACHERS WITH PROFESSIONAL QUALIFICATION : MALE (PGCMTCH),CONTRACTUAL TEACHERS WITH PROFESSIONAL QUALIFICATION : FEMALE (PGCFTCH),TOTAL CONTRACTUAL TEACHERS: MALE (PCMTCH),TOTAL CONTRACTUAL TEACHERS: FEMALE (PCFTCH),GRADE 1 (C1 B),GRADE 2 (C2 B),GRADE 3 (C3 B),GRADE 4 (C4 B),GRADE 5 (C5 B),GRADE 6 (C6 B),GRADE 7 (C7 B),GRADE 8 (C8 B),GRADE 9 (C9 B),GRADE 1 (C1 G),GRADE 2 (C2 G),GRADE 3 (C3 G),GRADE 4 (C4 G),GRADE 5 (C5 G),GRADE 6 (C6 G),GRADE 7 (C7 G),GRADE 8 (C8 G),GRADE 9 (C9 G),(C15A),(C68A),GRADE 1 (C1 BD),GRADE 2 (C2 BD),GRADE 3 (C3 BD),GRADE 4 (C4 BD),GRADE 5 (C5 BD),GRADE 6 (C6 BD),GRADE 7 (C7 BD),GRADE 8 (C8 BD),GRADE 1 (C1 GD),GRADE 2 (C2 GD),GRADE 3 (C3 GD),GRADE 4 (C4 GD),GRADE 5 (C5 GD),GRADE 6 (C6 GD),GRADE 7 (C7 GD),GRADE 8 (C8 GD),GRADE 1 (C1 BR),GRADE 2 (C2 BR),GRADE 3 (C3 BR),GRADE 4 (C4 BR),GRADE 5 (C5 BR),GRADE 6 (C6 BR),GRADE 7 (C7 BR),GRADE 8 (C8 BR),GRADE 9 (C9 BR),GRADE 1 (C1 GR),GRADE 2 (C2 GR),GRADE 3 (C3 GR),GRADE 4 (C4 GR),GRADE 5 (C5 GR),GRADE 6 (C6 GR),GRADE 7 (C7 GR),GRADE 8 (C8 GR),GRADE 9 (C9 GR),TOTAL (SCPTOT),GIRLS (SCPTOT G),TOTAL (SCUTOT),GIRLS (SCUTOT G),TOTAL (STPTOT),GIRLS (STPTOT G),TOTAL (STUTOT),GIRLS (STUTOT G),TOTAL (OBPTOT),GIRLS (OBUTOT),TOTAL (OBPTOT G),GIRLS (OBUTOT G),TOTAL (MUPTOT),GIRLS (MUUTOT),TOTAL (MUPTOT G),GIRLS (MUUTOT G),BLIND (BLC1),LOW VISION (LVC1),HEARING IMPAIRMENT (HEC1),SPEECH IMPAIRMENT (SPC1),LOCOMOTOR IMPAIRMENT (LOC1),MENTAL RETARDATION (MEC1),LEARNING DISABILITY (LEC1),CEREBRAL PALSY (CPC1),AUTISM (AUC1),MULTIPLE (MUC1),BLIND (BLC2),LOW VISION (LVC2),HEARING IMPAIRMENT (HEC2),SPEECH IMPAIRMENT (SPC2),LOCOMOTOR IMPAIRMENT (LOC2),MENTAL RETARDATION (MEC2),LEARNING DISABILITY (LEC2),CEREBRAL PALSY (CPC2),AUTISM (AUC2),MULTIPLE (MUC2),BLIND (BLC3),LOW VISION (LVC3),HEARING IMPAIRMENT (HEC3),SPEECH IMPAIRMENT (SPC3),LOCOMOTOR IMPAIRMENT (LOC3),MENTAL RETARDATION (MEC3),LEARNING DISABILITY (LEC3),CEREBRAL PALSY (CPC3),AUTISM (AUC3),MULTIPLE (MUC3),BLIND (BLC4),LOW VISION (LVC4),HEARING IMPAIRMENT (HEC4),SPEECH IMPAIRMENT (SPC4),LOCOMOTOR IMPAIRMENT (LOC4),MENTAL RETARDATION (MEC4),LEARNING DISABILITY (LEC4),CEREBRAL PALSY (CPC4),AUTISM (AUC4),MULTIPLE (MUC4),BLIND (BLC5),LOW VISION (LVC5),HEARING IMPAIRMENT (HEC5),SPEECH IMPAIRMENT (SPC5),LOCOMOTOR IMPAIRMENT (LOC5),MENTAL RETARDATION (MEC5),LEARNING DISABILITY (LEC5),CEREBRAL PALSY (CPC5),AUTISM (AUC5),MULTIPLE (MUC5),BLIND (BLC6),LOW VISION (LVC6),HEARING IMPAIRMENT (HEC6),SPEECH IMPAIRMENT (SPC6),LOCOMOTOR IMPAIRMENT (LOC6),MENTAL RETARDATION (MEC6),LEARNING DISABILITY (LEC6),CEREBRAL PALSY (CPC6),AUTISM (AUC6),MULTIPLE (MUC6),BLIND (BLC7),LOW VISION (LVC7),HEARING IMPAIRMENT (HEC7),SPEECH IMPAIRMENT (SPC7),LOCOMOTOR IMPAIRMENT (LOC7),MENTAL RETARDATION (MEC7),LEARNING DISABILITY (LEC7),C

# Crime data 2015-16

In [7]:
crimedf    = [dataCrime,dataVioCrm,dataCyberCrm,dataChldCrm,dataTrafficing,dataMissChildren,dataRapeVictm,dataKidnapping,dataJuvenileCrm,dataMurderVictm,dataCorruption,dataCurSeized,dataJuvArrest,dataMrdrMotive]
crimedfCom = reduce(lambda left,right: pd.merge(left,right, on=['STATE NAME']),crimedf)
crimedfCom.head()

,Unnamed: 0_x,STATE NAME,CRIME (2014),CRIME (2015),CRIME (2016),CRIME PER SHARE (STATE),CRIME RATE,Unnamed: 0_y,VIOLENT (MURDER),VIOLENT (CULPABLE HOMICIDE),VIOLENT (DOWRY DEATHS),VIOLENT (INFANTICIDE),VIOLENT (FOETICIDE),VIOLENT (ATTEMPT TO MURDER),VIOLENT (ATTEMPT TO HOMICIDE),VIOLENT (GRIEVOUS HURT),VIOLENT (KIDNAPPING & ABDUCTION),VIOLENT (RAPE),VIOLENT (ATTEMPT TO RAPE),VIOLENT (RIOT),VIOLENT (ROBERY),VIOLENT (DACOITY),VIOLENT (ARSON),VIOLENT TOTAL,Unnamed: 0_x,CYBER CRIME (2014),CYBER CRIME (2015),CYBER CRIME (2016),CYBER CRIME (PER SHARE),CYBER CRIME (RATE),Unnamed: 0_y,CHILDREN CRIME (2014),CHILDREN CRIME (2015),CHILDREN CRIME (2016),CHILDREN CRIME (PER SHARE),CHILDREN CRIME (RATE),Unnamed: 0_x,TRAFFICED BELOW 18 YRS (MALE),TRAFFICED BELOW 18 YRS (FEMALE),TRAFFICED BELOW 18 YRS (TOTAL),TRAFFICED ABOVE 18 YRS (MALE),TRAFFICED ABOVE 18 YRS (FEMALE),TRAFFICED ABOVE 18 YRS (TOTAL),TRAFFICED MALE (TOTAL),TRAFFICED FEMALE (TOTAL),TRAFFICED TOTAL (TOTAL),TRAFFICED FOR (FORCED LABOUR),TRAFFICED FOR (SEXUAL EXPLOITATION FOR PROSTITUTION),TRAFFICED FOR (DOMESTIC SERVITUDE),DOMESTIC SERVITUDE,TRAFFICED FOR (FORCED MARRIAGE),TRAFFICED FOR (PETTY CRIMES),TRAFFICED FOR (CHILD PORNOGRAPHY),TRAFFICED FOR (BEGGING),TRAFFICED FOR (DRUG PEDDLING),TRAFFICED FOR (REMOVAL OF ORGANS),TRAFFICED FOR (OTHER REASONS),TRAFFICED (TOTAL),TRAFFICED PERSON (ARRESTED),Unnamed: 0_y,CHILDREN MISSING (FEMALE),CHILDREN MISSING (MALE),CHILDREN MISSING (TOTAL),CHILDREN RECOVERED/TRACED (FEMALE),CHILDREN RECOVERED/TRACED (MALE),CHILDREN RECOVERED/TRACED (TOTAL),CHILDREN RECOVERY PER (FEMALE),CHILDREN RECOVERY PER (MALE),CHILDREN RECOVERY PER (TOTAL),Unnamed: 0_x,RAPE CASE REPORTED,RAPE VICTIMS BELOW 6 YEARS,RAPE VICTIMS 6-11 YEARS,RAPE VICTIMS 12-15 YEARS,RAPE VICTIMS 16-17 YEARS,RAPE VICTIMS CHILD (TOTAL),RAPE VICTIMS 18-29 YEARS,RAPE VICTIMS 30-44 YEARS,RAPE VICTIMS 45-59 YEARS,RAPE VICTIMS 60 YEARS & ABOVE,RAPE VICTIMS ADULT (TOTAL),RAPE VICTIMS (TOTAL),Unnamed: 0_y,KIDNAPPED & ABDUCTED (MALE),KIDNAPPED & ABDUCTED (FEMALE),KIDNAPPED & ABDUCTED (TOTAL),KIDNAPPED PERSON RECOVERED ALIVE (MALE),KIDNAPPED PERSON RECOVERED ALIVE (FEMALE),KIDNAPPED PERSON RECOVERED ALIVE (TOTAL),KIDNAPPED PERSON RECOVERED DEAD (MALE),KIDNAPPED PERSON RECOVERED DEAD (FEMALE),KIDNAPPED PERSON RECOVERED DEAD (TOTAL),KIDNAPPED PERSON RECOVERED (MALE),KIDNAPPED PERSON RECOVERED (FEMALE),KIDNAPPED PERSON RECOVERED (TOTAL),KIDNAPPED PERSON RECOVERY PER (MALE),KIDNAPPED PERSON RECOVERY PER (FEMALE),KIDNAPPED PERSON RECOVERY PER (TOTAL),KIDNAPPED PERSON UNRECOVERED (MALE),KIDNAPPED PERSON UNRECOVERED (FEMALE),KIDNAPPED PERSON UNRECOVERED (TOTAL),Unnamed: 0_x,JUVENILE CRIME (2014),JUVENILE CRIME (2015),JUVENILE CRIME (2016),JUVENILE CRIME (PER SHARE),JUVENILE CRIME (RATE),Unnamed: 0_y,MURDERED CHILD (MALE),MURDERED CHILD (FEMALE),MURDERED CHILD TOTAL (TOTAL),MURDERED ADULT (MALE),MURDERED ADULT (FEMALE),MURDERED ADULT TOTAL (TOTAL),MURDERED TOTAL (MALE),MURDERED TOTAL (FEMALE),MURDERED TOTAL (TOTAL),Unnamed: 0_x,CORRUPTION CASE (2014),CORRUPTION CASE (2015),CORRUPTION CASE (2016),CORRUPTION CASE (% SHARE),Unnamed: 0_y,DENOMINATION - 2000,DENOMINATION - 1000,DENOMINATION - 500,DENOMINATION - 100,DENOMINATION - 50,DENOMINATION - 20,DENOMINATION - 10,DENOMINATION - 5,DENOMINATION - 2,DENOMINATION - 1,TOTAL VALUE (IN RS.),Unnamed: 0_x,JUVENILE EDU (ILLITERATE),JUVENILE EDU (PRIMARY),JUVENILE EDU (ABOVE PRIMARY BELOW MATRIC),JUVENILE EDU (MATRIC/HSC & ABOVE),JUVENILE EDU (TOTAL),JUVENILE FAMILY BG (LIVING WITH PARENTS),JUVENILE FAMILY BG (LIVING WITH GUARDIANS),JUVENILE FAMILY BG (HOMELESS),JUVENILE FAMILY BG (TOTAL),Unnamed: 0_y,PERSONAL VENDETTA OR ENMITY,PROPERTY DISPUTE,GAIN,ILLICIT RELATIONSHIP,LOVE AFFAIRS,DOWRY,WATER OR MONEY DISPUTE,ROAD RAGE,EXTREMISM / NAXALISM,CASTEISM,ROBBERY/ EXTORTION,RAPE,CLASS CONFLICT,WITCH CRAFT,POLITICAL REASONS,LUNACY,HONOUR KILLING,COMMUNALISM,CHILD/ HUMAN SACRIFICE,OTHER CAUSES*,TOTAL MOTIVES
0,0,ANDHRA PRADESH,114604,110693,106774,3.6,206.4,0,1123,83,193,10,1,1795,0,604,917,994,190,657,315,63,519,7464,0,282,536,616,5.0,1.2,0,2059,1992,1847,1.7,11.8,0,0,44,44,0,311,311,0,355,355,2,736,11,36,0,3,0,0,0,0,95,883,599,0,1365,790,3324,1214,698,1912,60.2,53.3,57.5,0,994,17,43,142,261,463,436,85,9,2,532,995,0,628,1483,2111,83,248,331,0,0,0,83,248,331,13.2,16.7,15.7,545,1235,1780,0,883,1015,809,2.3,5.2,0,29,30,59,730,398,1128,759,428,1187,0,174,185,164,3.7,0,3,5002,8296,1240,0,0,0,0,0,0,9280000,0,228,427,475,99,1229,910,150,169,1229,0,85,96,47,138,9,49,21,0,3,1,0,5,0,8,0,0,2,0,0,659,1123
1,1,ARUNACHAL PRADESH,2843,2968,2534,0.1,192.3,1,46,6,1,0,0,46,0,235,112,92,15,8,63,10,31,665,1,18,6,4,0.0,0.3,1,134,181,133,0.1,28.3,1,0,2,2,0,1,1,0,3,3,0,0,0,0,1,0,0,0,0,0,0,1,5,1,29,9,61,24,9,33,51.1,64.3,54.1,1,92,3,12,25,10,50,32,7,2,1,42,92,1,37,109,146,27,68,95,0,0,0,27,68,95,73.0,62.4,65.1,10,41,51,1,81,66,57,0.2,12.1,1,0,1,1,38,10,48,38,11,49,1,11,15,14,0.3,1,3,0,118,0,0,0,0,0,0,0,65000,1,3,10,64,3,80,73,7,0,80,1,2,0,1,3,4,0,0,0,1,0,0,0,0,0,0,1,0,0,0,34,46
2,2,ASSAM,94337,103616,102250,3.4,313.9,2,1149,34,157,0,1,1257,17,9844,6126,1779,370,1671,940,156,664,24165,2,379,483,696,5.7,2.1,2,1385,2835,3964,3.7,33.3,2,34,96,130,52,67,119,86,163,249,36,51,0,5,0,0,0,0,0,0,0,92,98,2,857,524,2413,708,361,1069,48.0,38.4,44.3,2,1779,0,52,147,265,464,938,373,4,0,1315,1779,2,3230,16311,19541,60,189,249,0,0,0,60,189,249,1.9,1.2,1.3,3170,16122,19292,2,487,624,436,1.2,3.7,2,26,9,35,897,217,1114,923,226,1149,2,0,14,23,0.5,2,0,230,1088,127,266,1,3,0,0,0,800050,2,70,216,182,12,480,337,125,18,480,2,281,342,188,36,27,13,8,0,1,0,6,6,27,1,0,1,0,0,1,211,1149
3,3,BIHAR,177595,176973,164163,5.5,157.4,3,2581,150,987,0,0,6998,1364,12040,7324,1008,321,11617,1410,349,472,46621,3,114,242,309,2.5,0.3,3,2255,1917,3932,3.7,8.8,3,183,13,196,8,32,40,191,45,236,193,43,0,0,0,0,0,0,0,0,0,236,114,3,3730,1087,5896,2324,702,3026,53.7,44.7,51.3,3,1008,0,7,41,121,169,684,146,9,0,839,1008,3,3643,9163,12806,675,2261,2936,10,0,10,685,2261,2946,18.8,24.7,23.0,2958,6902,9860,3,4371,1658,2335,6.5,5.2,3,27,6,33,2240,320,2560,2267,326,2593,3,128,112,164,3.7,3,0,1895,3652,111,94,0,0,0,0,0,3736800,3,530,492,1216,388,2626,1910,648,68,2626,3,524,946,590,195,187,44,2,0,0,3,2,5,9,0,26,1,3,0,0,44,2581
4,4,CHHATTISGARH,58200,56692,55029,1.8,211.7,4,957,37,84,1,18,690,1,786,2071,1626,20,652,379,60,341,7723,4,123,103,90,0.7,0.3,4,4358,4469,4746,4.4,47.2,4,60,78,138,77,54,131,137,132,269,191,35,6,31,1,0,0,0,0,0,1,265,193,4,1643,619,3127,1483,568,2051,68.3,59.5,65.6,4,1626,33,79,340,532,984,475,150,13,5,643,1627,4,977,2253,3230,548,1041,1589,11,1,12,559,1042,1601,57.2,46.2,49.6,418,1211,1629,4,1691,1914,1953,5.4,19.4,4,44,32,76,588,324,912,632,356,988,4,55,50,61,1.4,4,0,0,0,0,0,0,0,0,0,0,0,4,135,857,1116,286,2394,2206,169,19,2394,4,60,75,17,72,52,14,9,2,73,0,1,6,2,17,4,4,1,0,2,546,957

# Census methods

In [8]:
# Geo code and geo level
geography = pd.read_csv('data/geography.csv',encoding='UTF-8')
geo = geography[['geo_level','geo_code','name']]

# Calculating country data
def setCountryData(df,cols):
    for x in cols:
         df.loc[df['geo_level'] == 'country', x]= df.loc[df['geo_level'] == 'state', x].sum()
    return df;


# Calculating geographic data
def getGeoData(df):
    cols = list(df.columns.values)[2:]
    df = df.replace(',','',regex=True)
    df[cols] = df[cols].astype(float)
    df = df.rename(index=str, columns={'STATE NAME': 'name'})
    dfState = df.groupby(['name'])[cols].sum().reset_index()
   
    dfDis   = df.groupby(['DISTRICT NAME'])[cols].sum().reset_index()
    dfDis   = dfDis.rename(index=str, columns={'DISTRICT NAME': 'name'})
    dfDis['name'] = dfDis['name'].str.title()
    
    dfCom = pd.concat([dfState, dfDis])
    dfgeo = geo.merge(dfCom ,on=['name'],how='left')
    dfgeo = dfgeo.sort_values(by=['geo_level','name'])
    dfgeo = dfgeo.fillna(method = 'bfill', axis=0).fillna(0)
    dfgeoCountry = setCountryData(dfgeo,cols)
    return dfgeoCountry

# Calculating census data
def getCensusData(df,varname):
    dfgeo = getGeoData(df)
    dfgeoFinal = pd.melt(dfgeo, id_vars=['geo_level', 'geo_code','name'], var_name=varname, value_name="total")
    dfgeoFinal = dfgeoFinal.sort_values(by=['geo_level','name']).reset_index().drop(['index'],axis=1).drop(['name'],axis=1)
    dfgeoFinal['total'] = dfgeoFinal['total'].astype(int)
    return  dfgeoFinal

# Calculating school data
def getSchooldata(schooldf):
    schooldf.columns = schooldf.columns.str.split('(').str[0]
    schooldf.columns = schooldf.columns.str.strip()
    Schooldfgeo      = getGeoData(schooldf)
    return Schooldfgeo

# India gdp manipulation

In [9]:
gdpddf   = CenElemGDP[['STATE NAME','DISTRICT NAME','GDP (in Rs. Cr.)|1999-00','GDP (in Rs. Cr.)|2000-01','GDP (in Rs. Cr.)|2001-02','GDP (in Rs. Cr.)|2002-03','GDP (in Rs. Cr.)|2003-04','GDP (in Rs. Cr.)|2004-05','GDP (in Rs. Cr.)|2005-06','GDP (in Rs. Cr.)|2006-07','GDP (in Rs. Cr.)|2007-08','GDP (in Rs. Cr.)|2008-09','GDP (in Rs. Cr.)|2009-10','GDP (in Rs. Cr.)|2010-11','GDP (in Rs. Cr.)|2011-12','GDP (in Rs. Cr.)|2012-13']]
gdpFinal = getCensusData(gdpddf ,'gdp')
gdpFinal['gdp'] = gdpFinal['gdp'].str.split('|').str[1]
gdpFinal.head()
#gdpFinal.to_csv('data/gdp.csv', index=False)

  geo_level geo_code      gdp    total
0   country       IN  1999-00  1179776
1   country       IN  2000-01  1212280
2   country       IN  2001-02  1258442
3   country       IN  2002-03  1298873
4   country       IN  2003-04  1399638

# Indian caste manipulation

In [10]:
casteMale   = CenElemGDP[['STATE NAME','DISTRICT NAME','Male_SC','Male_ST']]
casteMalegeo = getGeoData(casteMale)
casteMalegeo['sex'] = 'Male'
casteMaledf = pd.melt(casteMalegeo, id_vars=['geo_level','geo_code','name','sex'], var_name="caste", value_name="total")


casteFemale   = CenElemGDP[['STATE NAME','DISTRICT NAME','Female_SC','Female_ST']]
casteFemalegeo = getGeoData(casteFemale)
casteFemalegeo['sex'] = 'Female'
casteFemaledf = pd.melt(casteFemalegeo, id_vars=['geo_level','geo_code','name','sex'], var_name="caste", value_name="total")
casteFemaledf

casteFinal = pd.concat([casteMaledf, casteFemaledf])
casteFinal['caste'] = casteFinal['caste'].str.split('_').str[1]
casteFinal =  casteFinal.sort_values(by=['geo_level','name']).reset_index().drop(['index'],axis=1).drop(['name'],axis=1)
casteFinaldf = casteFinal[['geo_level','geo_code','caste','sex','total']]
casteFinaldf['total'] = casteFinaldf['total'].astype(int)
casteFinaldf.head()
#casteFinaldf.to_csv('data/caste.csv', index=False)

  geo_level geo_code caste     sex      total
0   country       IN    SC    Male  103869684
1   country       IN    ST    Male   53135542
2   country       IN    SC  Female   98163606
3   country       IN    ST  Female   52576987
4  district      532    SC    Male     242844

# Indian house hold size

In [11]:
household   = CenElemGDP[['STATE NAME','DISTRICT NAME','Household_size_1_person_Households','Household_size_2_persons_Households','Household_size_3_persons_Households','Household_size_4_persons_Households','Household_size_5_persons_Households','Household_size_6_8_persons_Households','Household_size_9_persons_and_above_Households']]
householddf = getCensusData(household,'household')
householddf['household'] = householddf['household'].str[15:24]
householddf = householddf.replace('_',' ',regex=True)
householddf.replace('6 8 perso','6-8 persons',inplace=True)
householddf.replace('9 persons','9 persons & above',inplace=True)
householddf['household'] = householddf['household'].str.strip()
householddf.head()
#householddf.to_csv('data/household.csv', index=False)

  geo_level geo_code  household     total
0   country       IN   1 person   9069695
1   country       IN  2 persons  24058914
2   country       IN  3 persons  33842453
3   country       IN  4 persons  56216057
4   country       IN  5 persons  46419606

# Drinking water source

In [12]:
drinking    = CenElemGDP[['STATE NAME','DISTRICT NAME','Main_source_of_drinking_water_Un_covered_well_Households','Main_source_of_drinking_water_Handpump_Tubewell_Borewell_Households','Main_source_of_drinking_water_Spring_Households','Main_source_of_drinking_water_River_Canal_Households','Main_source_of_drinking_water_Other_sources_Households','Main_source_of_drinking_water_Tank_Pond_Lake_Households','Main_source_of_drinking_water_Tapwater_Households','Main_source_of_drinking_water_Tubewell_Borehole_Households']]
drinking    = drinking.rename(index=str, columns={'Main_source_of_drinking_water_Un_covered_well_Households':'Un-covered well','Main_source_of_drinking_water_Handpump_Tubewell_Borewell_Households':'Handpump','Main_source_of_drinking_water_Spring_Households':'Spring','Main_source_of_drinking_water_River_Canal_Households':'River/Canal','Main_source_of_drinking_water_Tank_Pond_Lake_Households':'Tank/Pond/Lake','Main_source_of_drinking_water_Tapwater_Households':'Tap water','Main_source_of_drinking_water_Tubewell_Borehole_Households':'Tubewell/Borehole','Main_source_of_drinking_water_Other_sources_Households':'Other sources'})
drinkingdf  = getCensusData(drinking,'drinkingsource')
drinkingdf.head()
#drinkingdf.to_csv('data/drinkingsource.csv', index=False)

  geo_level geo_code   drinkingsource      total
0   country       IN  Un-covered well   23496100
1   country       IN         Handpump  103804950
2   country       IN           Spring    1330516
3   country       IN      River/Canal    1565963
4   country       IN    Other sources    3651946

# Schools by category

In [13]:
schoolsgov   =  CenElemGDP[['STATE NAME','DISTRICT NAME','PRIMARY ONLY (SCH1G)','PRIMARY WITH UPPER PRIMARY (SCH2G)','PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SCH3G)','UPPER PRIMARY ONLY (SCH4G)','UPPER PRIMARY WITH SEC./H.SEC (SCH5G)','PRIMARY WITH UPPER PRIMARY SEC (SCH6G)','UPPER PRIMARY WITH  SEC. (SCH7G)']]
schoolsgovdf =  getSchooldata(schoolsgov)
schoolsgovdf['type'] = 'Government'
schoolsgovdf

schoolspvt   = CenElemGDP[['STATE NAME','DISTRICT NAME','PRIMARY ONLY (SCH1P)','PRIMARY WITH UPPER PRIMARY (SCH2P)','PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SCH3P)','UPPER PRIMARY ONLY (SCH4P)','UPPER PRIMARY WITH SEC./H.SEC (SCH5P)','PRIMARY WITH UPPER PRIMARY SEC (SCH6P)','UPPER PRIMARY WITH  SEC. (SCH7P)']]
schoolspvtdf = getSchooldata(schoolspvt)
schoolspvtdf['type'] = 'Private'
schoolspvtdf

schoolsCom    = pd.concat([schoolsgovdf, schoolspvtdf])
schoolsCom    =  schoolsCom.sort_values(by=['geo_level','name'])
schoolsComdf  = pd.melt(schoolsCom, id_vars=['geo_level','geo_code','name','type'], var_name="schools", value_name="total")
schoolsComdf['total'] = schoolsComdf['total'].astype(int)
schoolsComdf['schools'] = schoolsComdf['schools'].str.capitalize()
schoolsComdf  =  schoolsComdf.sort_values(by=['geo_level','name','type']).reset_index().drop(['index'],axis=1).drop(['name'],axis=1)
schoolsComdf = schoolsComdf[['geo_level','geo_code','schools','type','total']]
schoolsComdf.head()
#schoolsComdf.to_csv('data/schools_type.csv', index=False)

  geo_level geo_code                               schools        type   total
0   country       IN                          Primary only  Government  595051
1   country       IN            Primary with upper primary  Government  146919
2   country       IN  Primary with upper primary sec/h.sec  Government   11622
3   country       IN                    Upper primary only  Government  102196
4   country       IN         Upper primary with sec./h.sec  Government   16730

# Schools by gender boys/girls

In [14]:
schoolboys   = CenElemGDP[['STATE NAME','DISTRICT NAME','PRIMARY ONLY (SCHBOY1)','PRIMARY WITH UPPER PRIMARY (SCHBOY2)','PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SCHBOY3)','UPPER PRIMARY ONLY (SCHBOY4)','UPPER PRIMARY WITH SEC./H.SEC (SCHBOY5)','PRIMARY WITH UPPER PRIMARY SEC (SCHBOY6)','UPPER PRIMARY WITH  SEC. (SCHBOY7)']]
schoolgirls  = CenElemGDP[['STATE NAME','DISTRICT NAME','PRIMARY ONLY (SCHGIR1)','PRIMARY WITH UPPER PRIMARY (SCHGIR2)','PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SCHGIR3)','UPPER PRIMARY ONLY (SCHGIR4)','UPPER PRIMARY WITH SEC./H.SEC (SCHGIR5)','PRIMARY WITH UPPER PRIMARY SEC (SCHGIR6)','UPPER PRIMARY WITH  SEC. (SCHGIR7)']]

schoolBoys =  getSchooldata(schoolboys)
schoolBoys['gender'] = 'Boys'

schoolGirls =  getSchooldata(schoolgirls)
schoolGirls['gender'] = 'Girls'

schoolsComb =  pd.concat([schoolBoys, schoolGirls])
schoolsComb =  schoolsComb.sort_values(by=['geo_level','name'])

schoolsCombdf  = pd.melt(schoolsComb, id_vars=['geo_level','geo_code','name','gender'], var_name="schools", value_name="total")
schoolsCombdf['total']   = schoolsCombdf['total'].astype(int)
schoolsCombdf['schools'] = schoolsCombdf['schools'].str.capitalize()
schoolsCombdf  =  schoolsCombdf.sort_values(by=['geo_level','name']).reset_index().drop(['index'],axis=1).drop(['name'],axis=1)
schoolsCombdf  =  schoolsCombdf[['geo_level','geo_code','schools','gender','total']]
schoolsCombdf.head()
#schoolsCombdf.to_csv('data/schools_gender.csv', index=False)

  geo_level geo_code                               schools gender   total
0   country       IN                          Primary only   Boys  702763
1   country       IN                          Primary only  Girls  704167
2   country       IN            Primary with upper primary   Boys  237996
3   country       IN            Primary with upper primary  Girls  239338
4   country       IN  Primary with upper primary sec/h.sec   Boys   36290

# Teachers by school category

In [15]:
teachersgov =  CenElemGDP[['STATE NAME','DISTRICT NAME','PRIMARY ONLY (TCH1G)','PRIMARY WITH UPPER PRIMARY (TCH2G)','PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCH3G)','UPPER PRIMARY ONLY (TCH4G)','UPPER PRIMARY WITH SEC./H.SEC (TCH5G)','PRIMARY WITH UPPER PRIMARY SEC (TCH6G)','UPPER PRIMARY WITH  SEC. (TCH7G)']]
TeachersGov = getSchooldata(teachersgov)
TeachersGov['type'] = 'Government'

teacherpvt  = CenElemGDP[['STATE NAME','DISTRICT NAME','PRIMARY ONLY (TCH1P)','PRIMARY WITH UPPER PRIMARY (TCH2P)','PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCH3P)','UPPER PRIMARY ONLY (TCH4P)','UPPER PRIMARY WITH SEC./H.SEC (TCH5P)','PRIMARY WITH UPPER PRIMARY SEC (TCH6P)','UPPER PRIMARY WITH  SEC. (TCH7P)']]
TeachersPvt = getSchooldata(teacherpvt)
TeachersPvt['type'] = 'Private'

teacherCom = pd.concat([TeachersGov, TeachersPvt])
teacherCom =  teacherCom.sort_values(by=['geo_level','name'])
teacherComdf  = pd.melt(teacherCom, id_vars=['geo_level','geo_code','name','type'], var_name="teachers", value_name="total")
teacherComdf['total']   = teacherComdf['total'].astype(int)
teacherComdf['teachers'] = teacherComdf['teachers'].str.capitalize()
teacherComdf  =  teacherComdf.sort_values(by=['geo_level','name','type']).reset_index().drop(['index'],axis=1).drop(['name'],axis=1)
teacherComdf  = teacherComdf[['geo_level','geo_code','teachers','type','total']]
teacherComdf.head()
#teacherComdf.to_csv('data/teachers_type.csv', index=False)

,geo_level,geo_code,teachers,type,total
0,country,IN,Primary only,Government,1624965
1,country,IN,Primary with upper primary,Government,960581
2,country,IN,Primary with upper primary sec/h.sec,Government,188355
3,country,IN,Upper primary only,Government,372018
4,country,IN,Upper primary with sec./h.sec,Government,382559

# Teachers by gender

In [16]:
teachersmale   = CenElemGDP[['STATE NAME','DISTRICT NAME','PRIMARY ONLY (TCHF1)','PRIMARY WITH UPPER PRIMARY (TCHF2)','PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHF3)','UPPER PRIMARY ONLY (TCHF4)','UPPER PRIMARY WITH SEC./H.SEC (TCHF5)','PRIMARY WITH UPPER PRIMARY SEC (TCHF6)','UPPER PRIMARY WITH  SEC. (TCHF7)']]
teachersfemale = CenElemGDP[['STATE NAME','DISTRICT NAME','PRIMARY ONLY (TCHM1)','PRIMARY WITH UPPER PRIMARY (TCHM2)','PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHM3)','UPPER PRIMARY ONLY (TCHM4)','UPPER PRIMARY WITH SEC./H.SEC (TCHM5)','PRIMARY WITH UPPER PRIMARY SEC (TCHM6)','UPPER PRIMARY WITH  SEC. (TCHM7)']]

teachersMale  = getSchooldata(teachersmale)
teachersMale['gender'] = 'Male'

teachersFemale = getSchooldata(teachersfemale)
teachersFemale['gender'] = 'Female'

teacherComb =  pd.concat([teachersMale, teachersFemale])
teacherComb =  teacherComb.sort_values(by=['geo_level','name'])

teacherCombdf  = pd.melt(teacherComb, id_vars=['geo_level','geo_code','name','gender'], var_name="teachers", value_name="total")
teacherCombdf['total']   = teacherCombdf['total'].astype(int)
teacherCombdf['teachers'] = teacherCombdf['teachers'].str.capitalize()
teacherCombdf  =  teacherCombdf.sort_values(by=['geo_level','name']).reset_index().drop(['index'],axis=1).drop(['name'],axis=1)
teacherCombdf  = teacherCombdf[['geo_level','geo_code','teachers','gender','total']]
teacherCombdf.head()
#teacherCombdf .to_csv('data/teachers_gender.csv', index=False)

  geo_level geo_code                              teachers  gender    total
0   country       IN                          Primary only    Male  1030237
1   country       IN                          Primary only  Female  1156193
2   country       IN            Primary with upper primary    Male   852226
3   country       IN            Primary with upper primary  Female   866535
4   country       IN  Primary with upper primary sec/h.sec    Male   451029

# Teachers by educational qualification

In [17]:
teachersbelowsec = CenElemGDP[['STATE NAME','DISTRICT NAME','PRIMARY ONLY (TCHBS1)','PRIMARY WITH UPPER PRIMARY (TCHBS2)','PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHBS3)','UPPER PRIMARY ONLY (TCHBS4)','UPPER PRIMARY WITH SEC./H.SEC (TCHBS5)','PRIMARY WITH UPPER PRIMARY SEC (TCHBS6)','UPPER PRIMARY WITH  SEC. (TCHBS7)']]
teacherssec      = CenElemGDP[['STATE NAME','DISTRICT NAME','PRIMARY ONLY (TCHSEC1)','PRIMARY WITH UPPER PRIMARY (TCHSEC2)','PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHSEC3)','UPPER PRIMARY ONLY (TCHSEC4)','UPPER PRIMARY WITH SEC./H.SEC (TCHSEC5)','PRIMARY WITH UPPER PRIMARY SEC (TCHSEC6)','UPPER PRIMARY WITH  SEC. (TCHSEC7)']]
teachershsec     = CenElemGDP[['STATE NAME','DISTRICT NAME','PRIMARY ONLY (TCHHS1)','PRIMARY WITH UPPER PRIMARY (TCHHS2)','PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHHS3)','UPPER PRIMARY ONLY (TCHHS4)','UPPER PRIMARY WITH SEC./H.SEC (TCHHS5)','PRIMARY WITH UPPER PRIMARY SEC (TCHHS6)','UPPER PRIMARY WITH  SEC. (TCHHS7)']]
teachersgrad     = CenElemGDP[['STATE NAME','DISTRICT NAME','PRIMARY ONLY (TCHGD1)','PRIMARY WITH UPPER PRIMARY (TCHGD2)','PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHGD3)','UPPER PRIMARY ONLY (TCHGD4)','UPPER PRIMARY WITH SEC./H.SEC (TCHGD5)','PRIMARY WITH UPPER PRIMARY SEC (TCHGD6)','UPPER PRIMARY WITH  SEC. (TCHGD7)']]
teacherspgrad    = CenElemGDP[['STATE NAME','DISTRICT NAME','PRIMARY ONLY (TCHPG1)','PRIMARY WITH UPPER PRIMARY (TCHPG2)','PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHPG3)','UPPER PRIMARY ONLY (TCHPG4)','UPPER PRIMARY WITH SEC./H.SEC (TCHPG5)','PRIMARY WITH UPPER PRIMARY SEC (TCHPG6)','UPPER PRIMARY WITH  SEC. (TCHPG7)']]
teachersmphill   = CenElemGDP[['STATE NAME','DISTRICT NAME','PRIMARY ONLY (TCHMD1)','PRIMARY WITH UPPER PRIMARY (TCHMD2)','PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHMD3)','UPPER PRIMARY ONLY (TCHMD4)','UPPER PRIMARY WITH SEC./H.SEC (TCHMD5)','PRIMARY WITH UPPER PRIMARY SEC (TCHMD6)','UPPER PRIMARY WITH  SEC. (TCHMD7)']]
teacherspd       = CenElemGDP[['STATE NAME','DISTRICT NAME','PRIMARY ONLY (TCHPD1)','PRIMARY WITH UPPER PRIMARY (TCHPD2)','PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TCHPD3)','UPPER PRIMARY ONLY (TCHPD4)','UPPER PRIMARY WITH SEC./H.SEC (TCHPD5)','PRIMARY WITH UPPER PRIMARY SEC (TCHPD6)','UPPER PRIMARY WITH  SEC. (TCHPD7)']]

teachersBelowSec = getSchooldata(teachersbelowsec)
teachersBelowSec['qualification'] = 'Below Secondary'
teachersBelowSec

teachersSec   = getSchooldata(teacherssec)
teachersSec['qualification'] = 'Secondary'
teachersSec

teachersHSec = getSchooldata(teachershsec)
teachersHSec['qualification'] = 'Higher Secondary'
teachersHSec

teachersGrad = getSchooldata(teachersgrad)
teachersGrad['qualification'] = 'Graduate'
teachersGrad

teachersPG  = getSchooldata(teacherspgrad)
teachersPG['qualification'] = 'Post Graduate'
teachersPG

teachersMphill = getSchooldata(teachersmphill)
teachersMphill['qualification'] = 'M.phill / Ph.D'
teachersMphill

teachersPD = getSchooldata(teacherspd)
teachersPD['qualification'] = 'Post Doctorate'
teachersPD

teachersQualComb =  pd.concat([teachersBelowSec, teachersSec , teachersHSec, teachersGrad, teachersPG, teachersMphill,teachersPD ])
teachersQual = pd.melt(teachersQualComb , id_vars=['geo_level','geo_code','name','qualification'], var_name="teachers", value_name="total")
teachersQual['teachers'] = teachersQual['teachers'].str.capitalize()
teachersQual['total'] = teachersQual['total'].astype(int)
teachersQual=  teachersQual.sort_values(by=['geo_level','name']).reset_index().drop(['index'],axis=1).drop(['name'],axis=1)
teachersQual = teachersQual[['geo_level','geo_code','teachers','qualification','total']]
teachersQual.head()
#teachersQual.to_csv('data/teachers_qualification.csv', index=False)

  geo_level geo_code      teachers     qualification   total
0   country       IN  Primary only   Below Secondary   25091
1   country       IN  Primary only         Secondary  196375
2   country       IN  Primary only  Higher Secondary  468803
3   country       IN  Primary only          Graduate  753458
4   country       IN  Primary only     Post Graduate  394896

# Students enrolnment

In [18]:
studentsgov = CenElemGDP[['STATE NAME','DISTRICT NAME','PRIMARY ONLY (ENR1G)','PRIMARY WITH UPPER PRIMARY (ENR2G)','PRIMARY WITH UPPER PRIMARY SEC/H.SEC (ENR3G)','UPPER PRIMARY ONLY (ENR4G)','UPPER PRIMARY WITH SEC./H.SEC (ENR5G)','PRIMARY WITH UPPER PRIMARY SEC (ENR6G)','UPPER PRIMARY WITH  SEC. (ENR7G)']]
StudentsGov = getSchooldata(studentsgov)
StudentsGov['type'] = 'Government'

studentspvt = CenElemGDP[['STATE NAME','DISTRICT NAME','PRIMARY ONLY (ENR1P)','PRIMARY WITH UPPER PRIMARY (ENR2P)','PRIMARY WITH UPPER PRIMARY SEC/H.SEC (ENR3P)','UPPER PRIMARY ONLY (ENR4P)','UPPER PRIMARY WITH SEC./H.SEC (ENR5P)','PRIMARY WITH UPPER PRIMARY SEC (ENR6P)','UPPER PRIMARY WITH  SEC. (ENR7P)']]
StudentsPvt = getSchooldata(studentspvt)
StudentsPvt['type'] = 'Private'

studentCom =  pd.concat([StudentsGov, StudentsPvt])
studentCom =  studentCom.sort_values(by=['geo_level','name'])
studentComdf  = pd.melt(studentCom, id_vars=['geo_level','geo_code','name','type'], var_name="students", value_name="total")
studentComdf['total']   = studentComdf['total'].astype(int)
studentComdf['students'] = studentComdf['students'].str.capitalize()
studentComdf  =  studentComdf.sort_values(by=['geo_level','name','type']).reset_index().drop(['index'],axis=1).drop(['name'],axis=1)
studentComdf  = studentComdf[['geo_level','geo_code','students','type','total']]
studentComdf.head()
#studentComdf.to_csv('data/students_type.csv', index=False)

,geo_level,geo_code,students,type,total
0,country,IN,Primary only,Government,43606123
1,country,IN,Primary with upper primary,Government,31388724
2,country,IN,Primary with upper primary sec/h.sec,Government,3224479
3,country,IN,Upper primary only,Government,9265039
4,country,IN,Upper primary with sec./h.sec,Government,5182196

# Girls enrolment by school type

In [19]:
enrolmentgirls    = CenElemGDP[['STATE NAME','DISTRICT NAME','PRIMARY ONLY (ENRG1)','PRIMARY WITH UPPER PRIMARY (ENRG2)','PRIMARY WITH UPPER PRIMARY SEC/H.SEC (ENRG3)','UPPER PRIMARY ONLY (ENRG4)','UPPER PRIMARY WITH SEC./H.SEC (ENRG5)','PRIMARY WITH UPPER PRIMARY SEC (ENRG6)','UPPER PRIMARY WITH  SEC. (ENRG7)']]
enrolmentGirls    =  getSchooldata(enrolmentgirls)
enrolmentGirlsdf  = pd.melt(enrolmentGirls, id_vars=['geo_level','geo_code','name'], var_name="girlsenrolment", value_name="total")
enrolmentGirlsdf['girlsenrolment'] = enrolmentGirlsdf['girlsenrolment'].str.capitalize()
enrolmentGirlsdf['total'] = enrolmentGirlsdf['total'].astype(int)
enrolmentGirlsdf =  enrolmentGirlsdf.sort_values(by=['geo_level','name']).reset_index().drop(['index'],axis=1).drop(['name'],axis=1)
enrolmentGirlsdf.head()
#enrolmentGirlsdf.to_csv('data/girlsenrolment.csv', index=False)

  geo_level geo_code                        girlsenrolment     total
0   country       IN                          Primary only  29104702
1   country       IN            Primary with upper primary  24793698
2   country       IN  Primary with upper primary sec/h.sec   6773424
3   country       IN                    Upper primary only   6569646
4   country       IN         Upper primary with sec./h.sec   4734447

# Schools with toilet facility

In [20]:
girlstoilet = CenElemGDP[['STATE NAME','DISTRICT NAME','PRIMARY ONLY (SGTOIL1)','PRIMARY WITH UPPER PRIMARY (SGTOIL2)','PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SGTOIL3)','UPPER PRIMARY ONLY (SGTOIL4)','UPPER PRIMARY WITH SEC./H.SEC (SGTOIL5)','PRIMARY WITH UPPER PRIMARY SEC (SGTOIL6)','UPPER PRIMARY WITH  SEC. (SGTOIL7)']]
girlsToilet = getSchooldata(girlstoilet)
girlsToilet['type'] = 'Girls toilet'

boystoilet = CenElemGDP[['STATE NAME','DISTRICT NAME','PRIMARY ONLY (SBTOIL1)','PRIMARY WITH UPPER PRIMARY (SBTOIL2)','PRIMARY WITH UPPER PRIMARY SEC/H.SEC (SBTOIL3)','UPPER PRIMARY ONLY (SBTOIL4)','UPPER PRIMARY WITH SEC./H.SEC (SBTOIL5)','PRIMARY WITH UPPER PRIMARY SEC (SBTOIL6)','UPPER PRIMARY WITH  SEC. (SBTOIL7)']]
boysToilet = getSchooldata(boystoilet)
boysToilet['type'] = 'Boys toilet'

toiletCom = pd.concat([girlsToilet, boysToilet])
toiletCom =  toiletCom.sort_values(by=['geo_level','name'])
toiletComdf  = pd.melt(toiletCom, id_vars=['geo_level','geo_code','name','type'], var_name="toilets", value_name="total")
toiletComdf['total']   = toiletComdf['total'].astype(int)
toiletComdf['toilets'] = toiletComdf['toilets'].str.capitalize()
toiletComdf  =  toiletComdf.sort_values(by=['geo_level','name','type']).reset_index().drop(['index'],axis=1).drop(['name'],axis=1)
toiletComdf  = toiletComdf[['geo_level','geo_code','toilets','type','total']]
toiletComdf.head()
#toiletComdf.to_csv('data/toilets_type.csv', index=False)

,geo_level,geo_code,toilets,type,total
0,country,IN,Primary only,Boys toilet,676055
1,country,IN,Primary with upper primary,Boys toilet,234043
2,country,IN,Primary with upper primary sec/h.sec,Boys toilet,36083
3,country,IN,Upper primary only,Boys toilet,116160
4,country,IN,Upper primary with sec./h.sec,Boys toilet,27846

# Schools with basic facilities

In [21]:
schoolsFac   =  CenElemGDP[['STATE NAME','DISTRICT NAME','TOTAL (SPLAYTOT)','TOTAL (SBNDRTOT)','TOTAL (SGTOILTOT)','TOTAL (SBTOILTOT)','TOTAL (SWATTOT)','TOTAL (SELETOT)','TOTAL (SCOMPTOT)']]
schoolsFac   =  schoolsFac.rename(index=str, columns={'STATE NAME': 'name','TOTAL (SPLAYTOT)':'Playground','TOTAL (SBNDRTOT)':'Boundry wall','TOTAL (SGTOILTOT)':'Girls toilet','TOTAL (SBTOILTOT)':'Boys toilet','TOTAL (SWATTOT)':'Drinking Water','TOTAL (SELETOT)':'Electricity','TOTAL (SCOMPTOT)':'Computers'})
schoolsFacdf =  getCensusData(schoolsFac,'facilities')
schoolsFacdf.head()

  geo_level geo_code      facilities    total
0   country       IN      Playground   745242
1   country       IN    Boundry wall   778671
2   country       IN    Girls toilet  1179918
3   country       IN     Boys toilet  1162194
4   country       IN  Drinking Water  1183486

# No of classrooms with condition school category

In [22]:
roomsgood      = CenElemGDP[['STATE NAME','DISTRICT NAME','PRIMARY ONLY (TOTCLGD1G)','PRIMARY WITH UPPER PRIMARY (TOTCLGD2G)','PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TOTCLGD3G)','UPPER PRIMARY ONLY (TOTCLGD4G)','UPPER PRIMARY WITH SEC./H.SEC (TOTCLGD5G)','PRIMARY WITH UPPER PRIMARY SEC (TOTCLGD6G)','UPPER PRIMARY WITH  SEC. (TOTCLGD7G)']]
roomsminorrepr = CenElemGDP[['STATE NAME','DISTRICT NAME','PRIMARY ONLY (TOTCLMI1G)','PRIMARY WITH UPPER PRIMARY (TOTCLMI2G)','PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TOTCLMI3G)','UPPER PRIMARY ONLY (TOTCLMI4G)','UPPER PRIMARY WITH SEC./H.SEC (TOTCLMI5G)','PRIMARY WITH UPPER PRIMARY SEC (TOTCLMI6G)','UPPER PRIMARY WITH  SEC. (TOTCLMI7G)']]
roomsmajorrepr = CenElemGDP[['STATE NAME','DISTRICT NAME','PRIMARY ONLY (TOTCLMJ1G)','PRIMARY WITH UPPER PRIMARY (TOTCLMJ2G)','PRIMARY WITH UPPER PRIMARY SEC/H.SEC (TOTCLMJ3G)','UPPER PRIMARY ONLY (TOTCLMJ4G)','UPPER PRIMARY WITH SEC./H.SEC (TOTCLMJ5G)','PRIMARY WITH UPPER PRIMARY SEC (TOTCLMJ6G)','UPPER PRIMARY WITH  SEC. (TOTCLMJ7G)']]

roomsGood = getSchooldata(roomsgood)
roomsGood['conditions'] = 'Good'
roomsGood

roomsMinorRepr = getSchooldata(roomsminorrepr)
roomsMinorRepr['conditions'] = 'Need Minor Repair'
roomsMinorRepr

roomsMajorRepr = getSchooldata(roomsmajorrepr)
roomsMajorRepr['conditions'] = 'Need Major Repair'

roomsComb =  pd.concat([roomsGood, roomsMinorRepr , roomsMajorRepr ])
roomsCombdf  = pd.melt(roomsComb, id_vars=['geo_level','geo_code','name','conditions'], var_name="classrooms", value_name="total")
roomsCombdf['classrooms'] = roomsCombdf['classrooms'].str.capitalize()
roomsCombdf['total'] = roomsCombdf['total'].astype(int)
roomsCombdf =  roomsCombdf.sort_values(by=['geo_level','name']).reset_index().drop(['index'],axis=1).drop(['name'],axis=1)
roomsCombdf  = roomsCombdf[['geo_level','geo_code','classrooms','conditions','total']]
roomsCombdf.head()
#roomsCombdf.to_csv('data/classrooms_conditions.csv', index=False)

  geo_level geo_code                  classrooms         conditions    total
0   country       IN                Primary only               Good  1995461
1   country       IN                Primary only  Need Minor Repair   339619
2   country       IN                Primary only  Need Major Repair   263568
3   country       IN  Primary with upper primary               Good  1569126
4   country       IN  Primary with upper primary  Need Minor Repair   159247

# Crime data manipulation at state level

# Crime data functions

In [23]:
def getCrimeData(df,varname):
    
    df   = df.rename(index=str, columns={'STATE NAME': 'name'})
    cols = list(df.columns.values)[1:]
    dfgeo =  geo.merge(df,on=['name'],how='left')
    dfgeogeodf = setCountryData(dfgeo,cols)
    dfgeoFinal = pd.melt( dfgeogeodf, id_vars=['geo_level', 'geo_code','name'], var_name=varname, value_name="total")
    dfgeoFinal[varname] = dfgeoFinal[varname].str.split('(').str[1].str.split(')').str[0].str.capitalize()
    dfgeoFinal = dfgeoFinal.fillna(0)
    dfgeoFinal = dfgeoFinal.sort_values(by=['geo_level','name']).reset_index().drop(['index'],axis=1).drop(['name'],axis=1)
    dfgeoFinal['total'] = dfgeoFinal['total'].astype(int)
    
    return dfgeoFinal;

def getCrimeDualData(df,varname,col,val):
    
    df   = df.rename(index=str, columns={'STATE NAME': 'name'})
    cols = list(df.columns.values)[1:]
    dfgeo =  geo.merge(df,on=['name'],how='left')
    dfgeogeodf = setCountryData(dfgeo,cols)
    dfgeogeodf[col] = val
    dfgeoFinal = pd.melt( dfgeogeodf, id_vars=['geo_level', 'geo_code','name',col], var_name=varname, value_name="total")
    dfgeoFinal[varname] = dfgeoFinal[varname].str.split('(').str[1].str.split(')').str[0].str.capitalize()
    dfgeoFinal = dfgeoFinal.fillna(0)
    dfgeoFinal = dfgeoFinal.sort_values(by=['geo_level','name']).reset_index().drop(['index'],axis=1).drop(['name'],axis=1)
    dfgeoFinal['total'] = dfgeoFinal['total'].astype(int)
    return dfgeoFinal;

# Age wise rape victims in India

In [24]:
rapev = crimedfCom[['STATE NAME','RAPE VICTIMS BELOW 6 YEARS','RAPE VICTIMS 6-11 YEARS','RAPE VICTIMS 12-15 YEARS','RAPE VICTIMS 16-17 YEARS','RAPE VICTIMS 18-29 YEARS','RAPE VICTIMS 30-44 YEARS','RAPE VICTIMS 45-59 YEARS','RAPE VICTIMS 60 YEARS & ABOVE']]
rapev = rapev.rename(index=str, columns={'STATE NAME': 'name', 'RAPE VICTIMS BELOW 6 YEARS': '0-6','RAPE VICTIMS 6-11 YEARS':'6-11','RAPE VICTIMS 12-15 YEARS':'12-15','RAPE VICTIMS 16-17 YEARS':'16-17','RAPE VICTIMS 18-29 YEARS':'18-29','RAPE VICTIMS 30-44 YEARS':'30-44','RAPE VICTIMS 45-59 YEARS':'45-59','RAPE VICTIMS 60 YEARS & ABOVE':'60 & Above'})
rapev = rapev[['name','0-6','6-11','12-15','16-17','18-29','30-44','45-59','60 & Above']]
rapevgeo =  geo.merge(rapev,on=['name'],how='left')
cols = ['0-6','6-11','12-15','16-17','18-29','30-44','45-59','60 & Above']
y = setCountryData(rapevgeo,cols)
rapevgeodf = pd.melt(y, id_vars=['geo_level', 'geo_code','name'], var_name="rape", value_name="total")
rapevgeodf =  rapevgeodf.sort_values(by=['geo_level','name']).reset_index().drop(['index'],axis=1).drop(['name'],axis=1)
rapevgeodf = rapevgeodf.fillna(0)
rapevgeodf['total'] =rapevgeodf['total'].astype(int)
rapevgeodf.head()
#rapevgeodf.to_csv('data/rape.csv', index=False)

  geo_level geo_code   rape  total
0   country       IN    0-6    520
1   country       IN   6-11   1596
2   country       IN  12-15   6091
3   country       IN  16-17   8656
4   country       IN  18-29  16462

# Year wise crimes in India

In [25]:
crimes = crimedfCom[['STATE NAME','CRIME (2014)','CRIME (2015)','CRIME (2016)']]
crimesdf = getCrimeData(crimes,'crimes')
crimesdf.head()
#crimesdf.to_csv('data/crimes.csv', index=False)

  geo_level geo_code crimes    total
0   country       IN   2014  2851563
1   country       IN   2015  2949400
2   country       IN   2016  2975711
3  district      532   2014        0
4  district      532   2015        0

# Year wise cyber crimes in India

In [26]:
cybercrimes = crimedfCom[['STATE NAME','CYBER CRIME (2014)','CYBER CRIME (2015)','CYBER CRIME (2016)']]
cybercrimesdf = getCrimeData(cybercrimes,'cybercrimes')
cybercrimesdf.head()
#cybercrimesdf.to_csv('data/cybercrimes.csv', index=False)

  geo_level geo_code cybercrimes  total
0   country       IN        2014   9622
1   country       IN        2015  11592
2   country       IN        2016  12317
3  district      532        2014      0
4  district      532        2015      0

# kidnapping by gender

In [27]:
kidnapped = crimedfCom[['STATE NAME','KIDNAPPED & ABDUCTED (MALE)','KIDNAPPED & ABDUCTED (FEMALE)']]
kidnappeddf = getCrimeData(kidnapped,'kidnapped')
kidnappeddf.head()
#kidnappeddf.to_csv('data/kidnapped.csv', index=False)

  geo_level geo_code kidnapped   total
0   country       IN      Male   42924
1   country       IN    Female  115823
2  district      532      Male       0
3  district      532    Female       0
4  district      146      Male       0

# Kidnapped recovery by gender

In [28]:
kidnappedRecAlive = crimedfCom[['STATE NAME','KIDNAPPED PERSON RECOVERED ALIVE (MALE)','KIDNAPPED PERSON RECOVERED ALIVE (FEMALE)']]
kidnappedRecAlivedf = getCrimeDualData(kidnappedRecAlive,'gender','recovery','Alive')

kidnappedRecDead  = crimedfCom[['STATE NAME','KIDNAPPED PERSON RECOVERED DEAD (MALE)','KIDNAPPED PERSON RECOVERED DEAD (FEMALE)']]
kidnappedRecDeaddf = getCrimeDualData(kidnappedRecDead,'gender','recovery','Dead')

kidnappingrecCom =  pd.concat([kidnappedRecAlivedf,kidnappedRecDeaddf])
kidnappingrecCom =  kidnappingrecCom.sort_values(by=['geo_level']).reset_index().drop(['index'],axis=1)
kidnappingrecCom.head()

  geo_level geo_code recovery  gender  total
0   country       IN    Alive    Male  18792
1   country       IN    Alive  Female  50482
2   country       IN     Dead    Male    182
3   country       IN     Dead  Female    143
4  district      458     Dead  Female      0

# Trafficing

In [29]:
trafficingMinor = crimedfCom[['STATE NAME','TRAFFICED BELOW 18 YRS (MALE)','TRAFFICED BELOW 18 YRS (FEMALE)']]
trafficingMinordf = getCrimeDualData(trafficingMinor,'gender','trafficing','Below 18 years')

trafficingMajor = crimedfCom[['STATE NAME','TRAFFICED ABOVE 18 YRS (MALE)','TRAFFICED ABOVE 18 YRS (FEMALE)']]
trafficingMajordf = getCrimeDualData(trafficingMajor,'gender','trafficing','Above 18 years')

trafficingCom =  pd.concat([trafficingMinordf,trafficingMajordf])
trafficingCom =  trafficingCom.sort_values(by=['geo_level']).reset_index().drop(['index'],axis=1)
trafficingCom.head()
#trafficingCom.to_csv('data/trafficing_gender.csv', index=False)

  geo_level geo_code      trafficing  gender  total
0   country       IN  Below 18 years    Male   4123
1   country       IN  Below 18 years  Female   4911
2   country       IN  Above 18 years    Male   1106
3   country       IN  Above 18 years  Female   5239
4  district      458  Above 18 years  Female      0

# Trafficing motives

In [30]:
trafficingMot = crimedfCom[['STATE NAME','TRAFFICED FOR (FORCED LABOUR)','TRAFFICED FOR (SEXUAL EXPLOITATION FOR PROSTITUTION)','TRAFFICED FOR (DOMESTIC SERVITUDE)','TRAFFICED FOR (FORCED MARRIAGE)','TRAFFICED FOR (PETTY CRIMES)','TRAFFICED FOR (CHILD PORNOGRAPHY)','TRAFFICED FOR (BEGGING)','TRAFFICED FOR (OTHER REASONS)']]
trafficingMotdf = getCrimeData(trafficingMot,'trafficingmotives')
trafficingMotdf.head()
#trafficingMotdf.to_csv('data/trafficingmotives.csv', index=False)

  geo_level geo_code                     trafficingmotives  total
0   country       IN                         Forced labour  10509
1   country       IN  Sexual exploitation for prostitution   4980
2   country       IN                    Domestic servitude   2590
3   country       IN                       Forced marriage    349
4   country       IN                          Petty crimes    212

# Violent crimes

In [31]:
viocrimes = crimedfCom[['STATE NAME','VIOLENT (MURDER)','VIOLENT (CULPABLE HOMICIDE)','VIOLENT (DOWRY DEATHS)','VIOLENT (INFANTICIDE)','VIOLENT (FOETICIDE)','VIOLENT (ATTEMPT TO MURDER)','VIOLENT (ATTEMPT TO HOMICIDE)','VIOLENT (GRIEVOUS HURT)','VIOLENT (KIDNAPPING & ABDUCTION)','VIOLENT (RAPE)','VIOLENT (ATTEMPT TO RAPE)','VIOLENT (RIOT)','VIOLENT (ROBERY)','VIOLENT (DACOITY)','VIOLENT (ARSON)']]
viocrimesdf = getCrimeData(viocrimes,'violentcrimes')
viocrimesdf.head()
#viocrimesdf.to_csv('data/violentcrimes.csv', index=False)

  geo_level geo_code      violentcrimes  total
0   country       IN             Murder  30450
1   country       IN  Culpable homicide   3203
2   country       IN       Dowry deaths   7621
3   country       IN        Infanticide     93
4   country       IN          Foeticide    144

# Yearly crimes against children

In [32]:
childcrimes =  crimedfCom[['STATE NAME','CHILDREN CRIME (2014)','CHILDREN CRIME (2015)','CHILDREN CRIME (2016)']]
childcrimesdf = getCrimeData(childcrimes,'childcrime')
childcrimesdf.head()
#childcrimesdf.to_csv('data/childcrime.csv', index=False)

  geo_level geo_code childcrime   total
0   country       IN       2014   89423
1   country       IN       2015   94172
2   country       IN       2016  106958
3  district      532       2014       0
4  district      532       2015       0

# Juvenile yearly crime

In [33]:
juvenilecrimes = crimedfCom[['STATE NAME','JUVENILE CRIME (2014)','JUVENILE CRIME (2015)','JUVENILE CRIME (2016)']]
juvenilecrimesdf = getCrimeData(juvenilecrimes,'juvenilecrime')
juvenilecrimesdf.head()
#juvenilecrimesdf.to_csv('data/juvenile.csv', index=False)

  geo_level geo_code juvenilecrime  total
0   country       IN          2014  38455
1   country       IN          2015  33433
2   country       IN          2016  35849
3  district      532          2014      0
4  district      532          2015      0

# Juvenile educational background

In [34]:
juveniledu  = crimedfCom[['STATE NAME','JUVENILE EDU (ILLITERATE)','JUVENILE EDU (PRIMARY)','JUVENILE EDU (ABOVE PRIMARY BELOW MATRIC)','JUVENILE EDU (MATRIC/HSC & ABOVE)']]
juveniledudf = getCrimeData(juveniledu,'juveniledu')
juveniledudf.head()
#juveniledudf.to_csv('data/juveniledu.csv', index=False)

  geo_level geo_code                  juveniledu  total
0   country       IN                  Illiterate   5412
1   country       IN                     Primary  14501
2   country       IN  Above primary below matric  20014
3   country       IN          Matric/hsc & above   4244
4  district      532                  Illiterate      0

# Juvenile family background

In [35]:
juvenilefmlbg  = crimedfCom[['STATE NAME','JUVENILE FAMILY BG (LIVING WITH PARENTS)','JUVENILE FAMILY BG (LIVING WITH GUARDIANS)','JUVENILE FAMILY BG (HOMELESS)']]
juvenilefmlbgdf = getCrimeData(juvenilefmlbg,'juvenilefamily')
juvenilefmlbgdf.head()
#juvenilefmlbgdf.to_csv('data/juvenilefamily.csv', index=False)

  geo_level geo_code         juvenilefamily  total
0   country       IN    Living with parents  38061
1   country       IN  Living with guardians   4550
2   country       IN               Homeless   1560
3  district      532    Living with parents      0
4  district      532  Living with guardians      0

# Murder victims in India

In [36]:
murderChild   = crimedfCom[['STATE NAME','MURDERED CHILD (MALE)','MURDERED CHILD (FEMALE)']]
murderChilddf = getCrimeDualData(murderChild,'gender','murder','Child')
murderChilddf

murderAdult = crimedfCom[['STATE NAME','MURDERED ADULT (MALE)','MURDERED ADULT (FEMALE)']]
murderAdultdf = getCrimeDualData(murderAdult,'gender','murder','Adult')

murderCom =  pd.concat([murderChilddf,murderAdultdf])
murderCom =  murderCom.sort_values(by=['geo_level']).reset_index().drop(['index'],axis=1)
murderCom.head()
#murderCom.to_csv('data/murder_gender.csv', index=False)

  geo_level geo_code murder  gender  total
0   country       IN  Child    Male    958
1   country       IN  Child  Female    817
2   country       IN  Adult    Male  21650
3   country       IN  Adult  Female   8071
4  district      458  Adult  Female      0

# Murder motives

In [37]:
def getCrimeDataWCC(df,varname):
    
    df   = df.rename(index=str, columns={'STATE NAME': 'name'})
    cols = list(df.columns.values)[1:]
    dfgeo =  geo.merge(df,on=['name'],how='left')
    dfgeogeodf = setCountryData(dfgeo,cols)
    dfgeoFinal = pd.melt( dfgeogeodf, id_vars=['geo_level', 'geo_code','name'], var_name=varname, value_name="total")
    dfgeoFinal[varname] = dfgeoFinal[varname].str.capitalize()
    dfgeoFinal = dfgeoFinal.fillna(0)
    dfgeoFinal = dfgeoFinal.sort_values(by=['geo_level','name']).reset_index().drop(['index'],axis=1).drop(['name'],axis=1)
    dfgeoFinal['total'] = dfgeoFinal['total'].astype(int)
    
    return dfgeoFinal;

murdermot = crimedfCom[['STATE NAME','PERSONAL VENDETTA OR ENMITY','PROPERTY DISPUTE','GAIN','ILLICIT RELATIONSHIP','LOVE AFFAIRS','DOWRY','WATER OR MONEY DISPUTE','ROAD RAGE','EXTREMISM / NAXALISM','CASTEISM','ROBBERY/ EXTORTION','RAPE','CLASS CONFLICT','POLITICAL REASONS','COMMUNALISM']]
murdermotdf = getCrimeDataWCC(murdermot,'murdermotive')
murdermotdf.head()
#murdermotdf.to_csv('data/murdermotive.csv', index=False)

  geo_level geo_code                 murdermotive  total
0   country       IN  Personal vendetta or enmity   5179
1   country       IN             Property dispute   3424
2   country       IN                         Gain   2270
3   country       IN         Illicit relationship   1671
4   country       IN                 Love affairs   1493

# Corruptions cases

In [38]:
corruptionCases   = crimedfCom[['STATE NAME','CORRUPTION CASE (2014)','CORRUPTION CASE (2015)','CORRUPTION CASE (2016)']]
corruptionCasesdf = getCrimeData(corruptionCases,'corruptioncase')
corruptionCasesdf.head()
#corruptionCasesdf.to_csv('data/corruptioncase.csv', index=False)

  geo_level geo_code corruptioncase  total
0   country       IN           2014   4966
1   country       IN           2015   5250
2   country       IN           2016   4439
3  district      532           2014      0
4  district      532           2015      0